# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Red Hat, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: anaconda 17.28.3\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2012-06-08 14:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"

#: anaconda:350
msgid "Press <enter> for a shell"
msgstr ""

#: anaconda:364
#, c-format
msgid ""
"%s requires %s MB of memory to install, but you only have %s MB on this "
"machine.\n"
msgstr ""

#: anaconda:366
#, c-format
msgid ""
"The %s graphical installer requires %s MB of memory, but you only have %s MB."
msgstr ""

#: anaconda:371
msgid "Not enough RAM"
msgstr ""

#: anaconda:372
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""

#: anaconda:375
msgid " Starting text mode."
msgstr ""

#: anaconda:402 pyanaconda/rescue.py:347 pyanaconda/rescue.py:379
#: pyanaconda/rescue.py:392 pyanaconda/rescue.py:460 pyanaconda/rescue.py:477
#: pyanaconda/rescue.py:488 pyanaconda/text.py:546
#: pyanaconda/textw/constants_text.py:44
msgid "OK"
msgstr ""

#: anaconda:495
msgid "Would you like to use VNC?"
msgstr ""

#: anaconda:496
msgid ""
"Text mode provides a limited set of installation options. It does not allow "
"you to specify your own partitioning layout or package selections. Would you "
"like to use VNC mode instead?"
msgstr ""

#: anaconda:517
msgid "DISPLAY variable not set. Starting text mode."
msgstr ""

#: anaconda:525
msgid "Graphical installation is not available. Starting text mode."
msgstr ""

#: pyanaconda/backend.py:132
#, python-format
msgid "%s Upgrading %s\n"
msgstr ""

#: pyanaconda/backend.py:134
#, python-format
msgid "%s Installing %s\n"
msgstr ""

#: pyanaconda/bootloader.py:245
msgid "/boot filesystem"
msgstr ""

#: pyanaconda/bootloader.py:477
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following raid levels: %s."
msgstr ""

#: pyanaconda/bootloader.py:485
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following metadata "
"versions: %s."
msgstr ""

#: pyanaconda/bootloader.py:493
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following device types: %s."
msgstr ""

#: pyanaconda/bootloader.py:509
#, python-format
msgid "%s must have one of the following disklabel types: %s."
msgstr ""

#: pyanaconda/bootloader.py:521 pyanaconda/bootloader.py:665
#, python-format
msgid "%s cannot be of type %s."
msgstr ""

#: pyanaconda/bootloader.py:527
#, python-format
msgid "%s must be mounted on one of %s."
msgstr ""

#: pyanaconda/bootloader.py:539
#, python-format
msgid "%s must be between %d and %d MB in size"
msgstr ""

#: pyanaconda/bootloader.py:544
#, python-format
msgid "%s must not be smaller than %dMB."
msgstr ""

#: pyanaconda/bootloader.py:553
#, python-format
msgid "%s must not be larger than %dMB."
msgstr ""

#: pyanaconda/bootloader.py:571
#, python-format
msgid "%s must be within the first %dMB of the disk."
msgstr ""

#: pyanaconda/bootloader.py:581
#, python-format
msgid "%s must be on a primary partition."
msgstr ""

#: pyanaconda/bootloader.py:705 pyanaconda/bootloader.py:810
#, python-format
msgid "%s cannot be on an encrypted block device."
msgstr ""

#: pyanaconda/bootloader.py:768
#, python-format
msgid "%s cannot be of type %s"
msgstr ""

#: pyanaconda/bootloader.py:1651
msgid ""
"Your BIOS-based system needs a special partition to boot with Fedora's new "
"disk label format (GPT). To continue, please create a 1MB 'BIOS Boot' type "
"partition."
msgstr ""

#: pyanaconda/bootloader.py:2328
msgid "Bootloader"
msgstr ""

#: pyanaconda/bootloader.py:2329
msgid "Installing bootloader."
msgstr ""

#: pyanaconda/bootloader.py:2336 pyanaconda/bootloader.py:2395
#: pyanaconda/gui.py:1093 pyanaconda/image.py:87
#: pyanaconda/installinterfacebase.py:74
#: pyanaconda/installinterfacebase.py:151 pyanaconda/packages.py:90
#: pyanaconda/packages.py:325 pyanaconda/text.py:419
#: pyanaconda/yuminstall.py:1528 pyanaconda/iw/blpasswidget.py:144
msgid "Warning"
msgstr ""

#: pyanaconda/bootloader.py:2337
msgid ""
"No kernel packages were installed on the system. Bootloader configuration "
"will not be changed."
msgstr ""

#: pyanaconda/bootloader.py:2396
msgid ""
"There was an error installing the bootloader.  The system may not be "
"bootable."
msgstr ""

#: pyanaconda/cmdline.py:66
msgid "Completed"
msgstr ""

#: pyanaconda/cmdline.py:74
msgid "In progress"
msgstr ""

#: pyanaconda/cmdline.py:87
#, python-format
msgid ""
"(%s)\n"
"Command line mode requires all choices to be specified in a kickstart "
"configuration file."
msgstr ""

#: pyanaconda/cmdline.py:104 pyanaconda/gui.py:1148
#: pyanaconda/kickstart.py:1343 pyanaconda/kickstart.py:1402
#: pyanaconda/kickstart.py:1410 pyanaconda/kickstart.py:1440
#: pyanaconda/kickstart.py:1450 pyanaconda/text.py:400
#, python-format
msgid ""
"The following error was found while parsing the kickstart configuration "
"file:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/cmdline.py:113
#, python-format
msgid ""
"(%s)\n"
"%s"
msgstr ""

#: pyanaconda/cmdline.py:126 pyanaconda/cmdline.py:131
#: pyanaconda/cmdline.py:137 pyanaconda/cmdline.py:142
msgid "Can't have a question in command line mode!"
msgstr ""

#: pyanaconda/cmdline.py:162
#, python-format
msgid "In interactive step can't continue. (%s)"
msgstr ""

#: pyanaconda/constants.py:52
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""

#: pyanaconda/constants.py:58
msgid " with the provider of this software."
msgstr ""

#: pyanaconda/constants.py:62
#, python-format
msgid " against anaconda at %s"
msgstr ""

#: pyanaconda/gui.py:110
msgid "An error occurred saving screenshots to disk."
msgstr ""

#: pyanaconda/gui.py:127
msgid "Screenshots Copied"
msgstr ""

#: pyanaconda/gui.py:128
msgid ""
"The screenshots have been saved in the directory:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"You can access these when you reboot and login as root."
msgstr ""

#: pyanaconda/gui.py:167
msgid "Saving Screenshot"
msgstr ""

#: pyanaconda/gui.py:168
#, python-format
msgid "A screenshot named '%s' has been saved."
msgstr ""

#: pyanaconda/gui.py:172
msgid "Error Saving Screenshot"
msgstr ""

#: pyanaconda/gui.py:173
msgid ""
"An error occurred while saving the screenshot.  If this occurred during "
"package installation, you may need to try several times for it to succeed."
msgstr ""

#: pyanaconda/gui.py:492 pyanaconda/text.py:146
msgid ""
"Choose a passphrase for the encrypted devices. You will be prompted for this "
"passphrase during system boot."
msgstr ""

#: pyanaconda/gui.py:511 pyanaconda/gui.py:519 pyanaconda/text.py:184
#: pyanaconda/text.py:194
msgid "Error with passphrase"
msgstr ""

#: pyanaconda/gui.py:512 pyanaconda/text.py:185
msgid "The passphrases you entered were different.  Please try again."
msgstr ""

#: pyanaconda/gui.py:520
msgid "The passphrase must be at least eight characters long."
msgstr ""

#: pyanaconda/gui.py:554 pyanaconda/text.py:222
#, python-format
msgid ""
"Device %s is encrypted. In order to access the device's contents during "
"installation you must enter the device's passphrase below."
msgstr ""

#: pyanaconda/gui.py:643 pyanaconda/gui.py:1337
#: pyanaconda/partIntfHelpers.py:159 pyanaconda/partIntfHelpers.py:344
#: pyanaconda/text.py:97 pyanaconda/text.py:98
#: pyanaconda/iw/account_gui.py:132 pyanaconda/textw/constants_text.py:48
msgid "Cancel"
msgstr ""

#: pyanaconda/gui.py:655 pyanaconda/gui.py:656 pyanaconda/gui.py:753
#: pyanaconda/gui.py:834 pyanaconda/gui.py:835 data/ui/anaconda.glade.h:3
msgid "_Debug"
msgstr ""

#: pyanaconda/gui.py:934
msgid "Wireless setup"
msgstr ""

#: pyanaconda/gui.py:935
msgid "Scanning access points for wireless devices"
msgstr ""

#: pyanaconda/gui.py:961 pyanaconda/textw/netconfig_text.py:399
msgid "Waiting for NetworkManager"
msgstr ""

#: pyanaconda/gui.py:962
#, python-format
msgid "Waiting for NetworkManager to activate these devices: %s"
msgstr ""

#: pyanaconda/gui.py:989
#, python-format
msgid "Failed to activate these network interfaces: %s"
msgstr ""

#: pyanaconda/gui.py:992
msgid "Network Configuration"
msgstr ""

#: pyanaconda/gui.py:1001
#, python-format
msgid "An error occurred trying to bring up the %s network interface."
msgstr ""

#: pyanaconda/gui.py:1003
msgid "Error Enabling Network"
msgstr ""

#: pyanaconda/gui.py:1058 pyanaconda/installinterfacebase.py:56
#: pyanaconda/iw/task_gui.py:321
msgid "Error Setting Up Repository"
msgstr ""

#: pyanaconda/gui.py:1059
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Please provide the correct information for installing %(productName)s."
msgstr ""

#: pyanaconda/gui.py:1094 pyanaconda/text.py:420
msgid ""
"You do not have an active network connection.  This is required by some "
"exception saving methods.  Would you like to configure your network now?"
msgstr ""

#: pyanaconda/gui.py:1100 pyanaconda/rescue.py:256 pyanaconda/text.py:426
#: pyanaconda/yuminstall.py:825 pyanaconda/yuminstall.py:1259
#: pyanaconda/iw/task_gui.py:309
msgid "No Network Available"
msgstr ""

#: pyanaconda/gui.py:1101 pyanaconda/text.py:427
msgid "Remote exception saving methods will not work."
msgstr ""

#: pyanaconda/gui.py:1116 pyanaconda/gui.py:1153 pyanaconda/gui.py:1337
#: pyanaconda/image.py:96 pyanaconda/installinterfacebase.py:208
#: pyanaconda/livecd.py:168 pyanaconda/packages.py:95
#: pyanaconda/packages.py:143 pyanaconda/upgrade.py:58
#: pyanaconda/upgrade.py:105 pyanaconda/upgrade.py:203
#: pyanaconda/yuminstall.py:262 pyanaconda/yuminstall.py:408
#: pyanaconda/yuminstall.py:830 pyanaconda/yuminstall.py:1008
#: pyanaconda/yuminstall.py:1013 pyanaconda/yuminstall.py:1050
#: pyanaconda/yuminstall.py:1102 pyanaconda/yuminstall.py:1108
#: pyanaconda/yuminstall.py:1264 pyanaconda/yuminstall.py:1279
#: pyanaconda/yuminstall.py:1334 pyanaconda/yuminstall.py:1524
#: pyanaconda/yuminstall.py:1557 pyanaconda/yuminstall.py:1580
#: pyanaconda/storage/__init__.py:99 pyanaconda/storage/__init__.py:105
#: pyanaconda/storage/__init__.py:107 pyanaconda/storage/__init__.py:199
#: pyanaconda/storage/__init__.py:251 pyanaconda/storage/__init__.py:2326
msgid "_Exit installer"
msgstr ""

#: pyanaconda/gui.py:1150 pyanaconda/text.py:402
msgid "Error Parsing Kickstart Config"
msgstr ""

#: pyanaconda/gui.py:1178
msgid "default:LTR"
msgstr ""

#: pyanaconda/gui.py:1246 pyanaconda/text.py:521
msgid "Error!"
msgstr ""

#: pyanaconda/gui.py:1247 pyanaconda/text.py:522
#, python-format
msgid ""
"An error occurred when attempting to load an installer interface component.\n"
"\n"
"className = %s"
msgstr ""

#: pyanaconda/gui.py:1252 pyanaconda/image.py:159 pyanaconda/image.py:177
#: pyanaconda/packages.py:342 pyanaconda/storage/__init__.py:2144
msgid "_Exit"
msgstr ""

#: pyanaconda/gui.py:1253 pyanaconda/image.py:159 pyanaconda/image.py:177
#: pyanaconda/livecd.py:168 pyanaconda/yuminstall.py:916
#: pyanaconda/yuminstall.py:1279 pyanaconda/yuminstall.py:1334
#: pyanaconda/yuminstall.py:1557
msgid "_Retry"
msgstr ""

#: pyanaconda/gui.py:1255 pyanaconda/storage/partitioning.py:386
msgid "The system will now reboot."
msgstr ""

#: pyanaconda/gui.py:1256 pyanaconda/packages.py:346
msgid "_Reboot"
msgstr ""

#: pyanaconda/gui.py:1258
msgid "Exiting"
msgstr ""

#: pyanaconda/gui.py:1334 pyanaconda/installinterfacebase.py:63
#: pyanaconda/livecd.py:126 pyanaconda/text.py:283 pyanaconda/upgrade.py:194
msgid "Exit installer"
msgstr ""

#: pyanaconda/gui.py:1335
msgid "Are you sure you wish to exit the installer?"
msgstr ""

#: pyanaconda/gui.py:1345
#, python-format
msgid "%s Installer"
msgstr ""

#: pyanaconda/gui.py:1351
msgid "Unable to load title bar"
msgstr ""

#: pyanaconda/gui.py:1449
msgid "Install Window"
msgstr ""

#: pyanaconda/image.py:88
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error."
msgstr ""

#: pyanaconda/image.py:97 pyanaconda/kickstart.py:1531
#: pyanaconda/kickstart.py:1570 pyanaconda/packages.py:95
#: pyanaconda/upgrade.py:58 pyanaconda/upgrade.py:105
#: pyanaconda/yuminstall.py:1339 pyanaconda/yuminstall.py:1524
#: pyanaconda/iw/partition_gui.py:1630 pyanaconda/storage/__init__.py:2327
msgid "_Continue"
msgstr ""

#: pyanaconda/image.py:151
msgid "Couldn't Mount ISO Source"
msgstr ""

#: pyanaconda/image.py:152
#, python-format
msgid ""
"An error occurred mounting the source device %s.  This may happen if your "
"ISO images are located on an advanced storage device like LVM or RAID, or if "
"there was a problem mounting a partition.  Click exit to abort the "
"installation."
msgstr ""

#: pyanaconda/image.py:168
msgid "Missing ISO 9660 Image"
msgstr ""

#: pyanaconda/image.py:169
msgid ""
"The installer has tried to mount the installation image, but cannot find it "
"on the hard drive.\n"
"\n"
"Please copy this image to the drive and click Retry.  Click Exit to abort "
"the installation."
msgstr ""

#: pyanaconda/image.py:230 pyanaconda/livecd.py:161
#: pyanaconda/partIntfHelpers.py:239 pyanaconda/text.py:375
#: pyanaconda/yuminstall.py:919 pyanaconda/yuminstall.py:1006
#: pyanaconda/yuminstall.py:1011 pyanaconda/yuminstall.py:1284
#: pyanaconda/yuminstall.py:1344 pyanaconda/yuminstall.py:1551
#: pyanaconda/yuminstall.py:1573 pyanaconda/iw/advanced_storage.py:378
#: pyanaconda/iw/advanced_storage.py:388 pyanaconda/iw/advanced_storage.py:438
#: pyanaconda/iw/autopart_type.py:95 pyanaconda/iw/cleardisks_gui.py:44
#: pyanaconda/iw/cleardisks_gui.py:54 pyanaconda/iw/filter_gui.py:443
#: pyanaconda/iw/lvm_dialog_gui.py:802 pyanaconda/iw/osbootwidget.py:209
#: pyanaconda/iw/osbootwidget.py:215 pyanaconda/iw/osbootwidget.py:224
#: pyanaconda/iw/partition_dialog_gui.py:385
#: pyanaconda/iw/raid_dialog_gui.py:219 pyanaconda/iw/raid_dialog_gui.py:345
#: pyanaconda/iw/task_gui.py:51 pyanaconda/iw/task_gui.py:151
#: pyanaconda/iw/task_gui.py:303 pyanaconda/iw/task_gui.py:466
#: pyanaconda/storage/__init__.py:247 pyanaconda/storage/__init__.py:2123
#: pyanaconda/storage/__init__.py:2145 pyanaconda/storage/__init__.py:2232
#: pyanaconda/storage/zfcp.py:375
msgid "Error"
msgstr ""

#: pyanaconda/image.py:231
#, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""

#: pyanaconda/installclass.py:68
msgid "Install on System"
msgstr ""

#: pyanaconda/installinterfacebase.py:57
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Installation can not continue."
msgstr ""

#: pyanaconda/installinterfacebase.py:75
#, python-format
msgid ""
"Disk %(unusedRaidMems)s contains BIOS RAID metadata, but is not part of any "
"recognized BIOS RAID sets. Ignoring disk %(unusedRaidMems)s."
msgid_plural ""
"Disks %(unusedRaidMems)s contain BIOS RAID metadata, but are not part of any "
"recognized BIOS RAID sets. Ignoring disks %(unusedRaidMems)s."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/installinterfacebase.py:103
#: data/ui/reinitialize-dialog.glade.h:3
msgid "Storage Device Warning"
msgstr ""

#: pyanaconda/installinterfacebase.py:152
#, python-format
msgid ""
"Error processing LVM.\n"
"There is inconsistent LVM data on %(msg)s.  You can reinitialize all related "
"PVs (%(pvs)s) which will erase the LVM metadata, or ignore which will "
"preserve the contents.  This action may also be applied to all other PVs "
"with inconsistent metadata."
msgstr ""

#: pyanaconda/installinterfacebase.py:159
#: pyanaconda/installinterfacebase.py:193
msgid "_Ignore"
msgstr ""

#: pyanaconda/installinterfacebase.py:160
msgid "Ignore _all"
msgstr ""

#: pyanaconda/installinterfacebase.py:161
msgid "_Re-initialize"
msgstr ""

#: pyanaconda/installinterfacebase.py:162
msgid "Re-ini_tialize all"
msgstr ""

#: pyanaconda/installinterfacebase.py:180
msgid "Unformatted DASD Device Found"
msgid_plural "Unformatted DASD Devices Found"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/installinterfacebase.py:182
#, python-format
msgid ""
"Format uninitialized DASD device?\n"
"\n"
"There is %d uninitialized DASD device on this system.  To continue "
"installation, the device must be formatted.  Formatting will remove any data "
"on this device."
msgid_plural ""
"Format uninitialized DASD devices?\n"
"\n"
"There are %d uninitialized DASD devices on this system.  To continue "
"installation, the devices must be formatted.  Formatting will remove any "
"data on these devices."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/installinterfacebase.py:193 pyanaconda/iw/partition_gui.py:887
msgid "_Format"
msgstr ""

#: pyanaconda/installinterfacebase.py:201
#, python-format
msgid ""
"The installation was stopped due to what seems to be a problem with your "
"hardware. The exact error message is:\n"
"\n"
"%s.\n"
"\n"
" The installer will now terminate."
msgstr ""

#: pyanaconda/installinterfacebase.py:204
msgid "Hardware Error Encountered"
msgstr ""

#: pyanaconda/iutil.py:859
msgid "Error determining boot device's disk name"
msgstr ""

#: pyanaconda/iutil.py:882
msgid "the device containing /boot"
msgstr ""

#: pyanaconda/iutil.py:884
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from %s to continue installation."
msgstr ""

#: pyanaconda/kickstart.py:126
#, python-format
msgid ""
"There was an error running the kickstart script at line %(lineno)s.  You may "
"examine the output in %(msgs)s.  This is a fatal error and installation will "
"be aborted.  Press the OK button to exit the installer."
msgstr ""

#: pyanaconda/kickstart.py:134 pyanaconda/kickstart.py:136
msgid "Scriptlet Failure"
msgstr ""

#: pyanaconda/kickstart.py:152
#, python-format
msgid ""
"Escrow certificate with url %s requires network to be enabled in loader or "
"configured in kickstart file."
msgstr ""

#: pyanaconda/kickstart.py:166
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/kickstart.py:489
msgid "Could not log into any iSCSI nodes at the portal."
msgstr ""

#: pyanaconda/kickstart.py:1475 pyanaconda/livecd.py:196
msgid "Post-Installation"
msgstr ""

#: pyanaconda/kickstart.py:1476
msgid "Running post-installation scripts"
msgstr ""

#: pyanaconda/kickstart.py:1491
msgid "Running pre-installation scripts"
msgstr ""

#: pyanaconda/kickstart.py:1522
msgid "Missing Package"
msgstr ""

#: pyanaconda/kickstart.py:1523
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist. Would you like to continue or abort this installation?"
msgstr ""

#: pyanaconda/kickstart.py:1529 pyanaconda/kickstart.py:1568
msgid "_Abort"
msgstr ""

#: pyanaconda/kickstart.py:1530 pyanaconda/kickstart.py:1569
msgid "_Ignore All"
msgstr ""

#: pyanaconda/kickstart.py:1560
msgid "Missing Group"
msgstr ""

#: pyanaconda/kickstart.py:1561
#, python-format
msgid ""
"You have specified that the group '%s' should be installed. This group does "
"not exist. Would you like to continue or abort this installation?"
msgstr ""

#: pyanaconda/kickstart.py:1653
#, python-format
msgid ""
"The kickstart configuration file is missing required information that "
"anaconda cannot prompt for.  Please add the following sections and try "
"again:\n"
"%s"
msgstr ""

#: pyanaconda/livecd.py:121
msgid "Unable to find image"
msgstr ""

#: pyanaconda/livecd.py:122
#, python-format
msgid ""
"The given location isn't a valid %s live CD to use as an installation source."
msgstr ""

#: pyanaconda/livecd.py:143
msgid "Copying live image to hard drive."
msgstr ""

#: pyanaconda/livecd.py:162
msgid ""
"There was an error installing the live image to your hard drive.  This could "
"be due to bad media.  Please verify your installation media.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"require reinstallation."
msgstr ""

#: pyanaconda/livecd.py:197
msgid ""
"Performing post-installation filesystem changes.  This may take several "
"minutes."
msgstr ""

#: pyanaconda/network.py:81
msgid "Hostname must be 255 or fewer characters in length."
msgstr ""

#: pyanaconda/network.py:87
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or '0-"
"9'"
msgstr ""

#: pyanaconda/network.py:92
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.'"
msgstr ""

#: pyanaconda/network.py:136
msgid "IP address is missing."
msgstr ""

#: pyanaconda/network.py:140
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""

#: pyanaconda/network.py:143
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr ""

#: pyanaconda/network.py:145
#, python-format
msgid "'%s' is an invalid IP address."
msgstr ""

#: pyanaconda/packages.py:91
msgid ""
"Filesystems have already been activated.  You cannot go back past this "
"point.\n"
"\n"
"Would you like to continue with the installation?"
msgstr ""

#: pyanaconda/packages.py:124
msgid "Resizing Failed"
msgstr ""

#: pyanaconda/packages.py:125
#, python-format
msgid "There was an error encountered while resizing the device %s."
msgstr ""

#: pyanaconda/packages.py:133
msgid "Migration Failed"
msgstr ""

#: pyanaconda/packages.py:134
#, python-format
msgid "An error was encountered while migrating filesystem on device %s."
msgstr ""

#: pyanaconda/packages.py:143
msgid "_File Bug"
msgstr ""

#: pyanaconda/packages.py:326
#, python-format
msgid ""
"Warning!  This is pre-release software!\n"
"\n"
"Thank you for downloading this pre-release of %(productName)s.\n"
"\n"
"This is not a final release and is not intended for use on production "
"systems.  The purpose of this release is to collect feedback from testers, "
"and it is not suitable for day to day usage.\n"
"\n"
"To report feedback, please visit:\n"
"\n"
"   %(bugzillaUrl)s\n"
"\n"
"and file a report against '%(fileagainst)s'.\n"
msgstr ""

#: pyanaconda/packages.py:342
msgid "_Install Anyway"
msgstr ""

#: pyanaconda/packages.py:345
msgid "Your system will now be rebooted..."
msgstr ""

#: pyanaconda/packages.py:346 pyanaconda/upgrade.py:202
#: pyanaconda/yuminstall.py:1013 pyanaconda/yuminstall.py:1108
#: pyanaconda/yuminstall.py:1526 pyanaconda/yuminstall.py:1580
#: pyanaconda/storage/__init__.py:107 data/ui/anaconda.glade.h:2
msgid "_Back"
msgstr ""

#: pyanaconda/packages.py:347
msgid "Warning! This is pre-release software!"
msgstr ""

#: pyanaconda/partIntfHelpers.py:47
msgid "Please enter a volume group name."
msgstr ""

#: pyanaconda/partIntfHelpers.py:51
msgid "Volume Group Names must be less than 128 characters"
msgstr ""

#: pyanaconda/partIntfHelpers.py:54
#, python-format
msgid "Error - the volume group name %s is not valid."
msgstr ""

#: pyanaconda/partIntfHelpers.py:59
msgid ""
"Error - the volume group name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""

#: pyanaconda/partIntfHelpers.py:69
msgid "Please enter a logical volume name."
msgstr ""

#: pyanaconda/partIntfHelpers.py:73
msgid "Logical Volume Names must be less than 128 characters"
msgstr ""

#: pyanaconda/partIntfHelpers.py:77
#, python-format
msgid "Error - the logical volume name %s is not valid."
msgstr ""

#: pyanaconda/partIntfHelpers.py:83
msgid ""
"Error - the logical volume name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""

#: pyanaconda/partIntfHelpers.py:111
#, python-format
msgid ""
"The mount point %s is invalid.  Mount points must start with '/' and cannot "
"end with '/', and must contain printable characters and no spaces."
msgstr ""

#: pyanaconda/partIntfHelpers.py:123 pyanaconda/partIntfHelpers.py:130
msgid "Unable To Delete"
msgstr ""

#: pyanaconda/partIntfHelpers.py:124
msgid "You must first select a partition to delete."
msgstr ""

#: pyanaconda/partIntfHelpers.py:155 pyanaconda/partIntfHelpers.py:343
#: pyanaconda/iw/lvm_dialog_gui.py:898
msgid "Confirm Delete"
msgstr ""

#: pyanaconda/partIntfHelpers.py:156
#, python-format
msgid "You are about to delete all partitions on the device '%s'."
msgstr ""

#: pyanaconda/partIntfHelpers.py:159 pyanaconda/partIntfHelpers.py:344
#: pyanaconda/iw/lvm_dialog_gui.py:901 pyanaconda/iw/lvm_dialog_gui.py:1552
#: pyanaconda/iw/osbootwidget.py:105 pyanaconda/iw/partition_gui.py:1843
#: pyanaconda/iw/partition_gui.py:1855
msgid "_Delete"
msgstr ""

#: pyanaconda/partIntfHelpers.py:206
msgid "Notice"
msgstr ""

#: pyanaconda/partIntfHelpers.py:207
#, python-format
msgid ""
"The following partitions were not deleted because they are in use:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/partIntfHelpers.py:222
msgid "Format as Swap?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:223
#, python-format
msgid ""
"%s has a partition type of 0x82 (Linux swap) but does not appear to be "
"formatted as a Linux swap partition.\n"
"\n"
"Would you like to format this partition as a swap partition?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:238
#, python-format
msgid "You need to select at least one hard drive to install %s."
msgstr ""

#: pyanaconda/partIntfHelpers.py:243
msgid ""
"You have chosen to use a pre-existing partition for this installation "
"without formatting it. We recommend that you format this partition to make "
"sure files from a previous operating system installation do not cause "
"problems with this installation of Linux. However, if this partition "
"contains files that you need to keep, such as home directories, then "
"continue without formatting this partition."
msgstr ""

#: pyanaconda/partIntfHelpers.py:251
msgid "Format?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:251 pyanaconda/iw/partition_gui.py:1628
msgid "_Modify Partition"
msgstr ""

#: pyanaconda/partIntfHelpers.py:251
msgid "Do _Not Format"
msgstr ""

#: pyanaconda/partIntfHelpers.py:259
msgid "Error with Partitioning"
msgstr ""

#: pyanaconda/partIntfHelpers.py:260
#, python-format
msgid ""
"The following critical errors exist with your requested partitioning scheme. "
"These errors must be corrected prior to continuing with your install of %"
"(productName)s.\n"
"\n"
"%(errorstr)s"
msgstr ""

#: pyanaconda/partIntfHelpers.py:276
msgid "Partitioning Warning"
msgstr ""

#: pyanaconda/partIntfHelpers.py:277
#, python-format
msgid ""
"The following warnings exist with your requested partition scheme.\n"
"\n"
"%s\n"
"\n"
"Would you like to continue with your requested partitioning scheme?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:291
msgid ""
"The following pre-existing partitions have been selected to be formatted, "
"destroying all data."
msgstr ""

#: pyanaconda/partIntfHelpers.py:294
msgid ""
"Select 'Yes' to continue and format these partitions, or 'No' to go back and "
"change these settings."
msgstr ""

#: pyanaconda/partIntfHelpers.py:300
msgid "Format Warning"
msgstr ""

#: pyanaconda/partIntfHelpers.py:327
#, python-format
msgid ""
"You are about to delete the volume group \"%s\".\n"
"\n"
"ALL logical volumes in this volume group will be lost!"
msgstr ""

#: pyanaconda/partIntfHelpers.py:331
#, python-format
msgid "You are about to delete the logical volume \"%s\"."
msgstr ""

#: pyanaconda/partIntfHelpers.py:334
msgid "You are about to delete a RAID device."
msgstr ""

#: pyanaconda/partIntfHelpers.py:336
#, python-format
msgid "You are about to delete the %s partition."
msgstr ""

#: pyanaconda/partIntfHelpers.py:340
#, python-format
msgid "You are about to delete the %(type)s %(name)s"
msgstr ""

#: pyanaconda/partIntfHelpers.py:351
msgid "Confirm Reset"
msgstr ""

#: pyanaconda/partIntfHelpers.py:352
msgid ""
"Are you sure you want to reset the partition table to its original state?"
msgstr ""

#: pyanaconda/partIntfHelpers.py:361
msgid "No authentication"
msgstr ""

#: pyanaconda/partIntfHelpers.py:362
msgid "CHAP pair"
msgstr ""

#: pyanaconda/partIntfHelpers.py:363
msgid "CHAP pair and a reverse pair"
msgstr ""

#: pyanaconda/partIntfHelpers.py:364
msgid "Use the credentials from the discovery step"
msgstr ""

#: pyanaconda/partIntfHelpers.py:472
msgid "iSCSI Nodes"
msgstr ""

#: pyanaconda/partIntfHelpers.py:473
msgid "No new iSCSI nodes discovered"
msgstr ""

#: pyanaconda/partIntfHelpers.py:514
msgid "iSCSI Error"
msgstr ""

#: pyanaconda/partIntfHelpers.py:519
msgid "Discovery"
msgstr ""

#: pyanaconda/partIntfHelpers.py:519
msgid "Login"
msgstr ""

#: pyanaconda/partIntfHelpers.py:520
#, python-format
msgid "iSCSI %s Error"
msgstr ""

#: pyanaconda/platform.py:58
msgid "bootloader device"
msgstr ""

#: pyanaconda/platform.py:59 data/ui/create-storage.glade.h:15
msgid "RAID Device"
msgstr ""

#: pyanaconda/platform.py:60
msgid "First sector of boot partition"
msgstr ""

#: pyanaconda/platform.py:157
msgid "Master Boot Record"
msgstr ""

#: pyanaconda/platform.py:193
msgid "EFI System Partition"
msgstr ""

#: pyanaconda/platform.py:222
msgid "Apple EFI Boot Partition"
msgstr ""

#: pyanaconda/platform.py:247
msgid "PReP Boot Partition"
msgstr ""

#: pyanaconda/platform.py:270
msgid "Apple Bootstrap Partition"
msgstr ""

#: pyanaconda/platform.py:299
msgid "DASD"
msgstr ""

#: pyanaconda/platform.py:300
msgid "zFCP"
msgstr ""

#: pyanaconda/rescue.py:215 pyanaconda/rescue.py:368 pyanaconda/rescue.py:453
#, python-format
msgid "Run %s to unmount the system when you are finished."
msgstr ""

#: pyanaconda/rescue.py:218
msgid "When finished please exit from the shell and your system will reboot."
msgstr ""

#: pyanaconda/rescue.py:232
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr ""

#: pyanaconda/rescue.py:250
msgid "Setup Networking"
msgstr ""

#: pyanaconda/rescue.py:251
msgid "Do you want to start the network interfaces on this system?"
msgstr ""

#: pyanaconda/rescue.py:252 pyanaconda/textw/constants_text.py:56
msgid "Yes"
msgstr ""

#: pyanaconda/rescue.py:252 pyanaconda/rescue.py:254
#: pyanaconda/textw/constants_text.py:60
msgid "No"
msgstr ""

#: pyanaconda/rescue.py:257
msgid ""
"Unable to activate a networking device.  Networking will not be available in "
"rescue mode."
msgstr ""

#: pyanaconda/rescue.py:293 pyanaconda/rescue.py:375 pyanaconda/rescue.py:385
#: pyanaconda/rescue.py:456 pyanaconda/rescue.py:488
msgid "Rescue"
msgstr ""

#: pyanaconda/rescue.py:294
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.  If you need to activate SAN devices choose "
"'Advanced'.\n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""

#: pyanaconda/rescue.py:305 pyanaconda/iw/partition_gui.py:774
#: pyanaconda/storage/__init__.py:159 pyanaconda/storage/devicetree.py:94
msgid "Continue"
msgstr ""

#: pyanaconda/rescue.py:305 pyanaconda/rescue.py:314
msgid "Read-Only"
msgstr ""

#: pyanaconda/rescue.py:305 pyanaconda/rescue.py:307
#: pyanaconda/storage/__init__.py:2144
msgid "Skip"
msgstr ""

#: pyanaconda/rescue.py:305 pyanaconda/rescue.py:310
msgid "Advanced"
msgstr ""

#: pyanaconda/rescue.py:344
msgid "System to Rescue"
msgstr ""

#: pyanaconda/rescue.py:345
msgid "Which device holds the root partition of your installation?"
msgstr ""

#: pyanaconda/rescue.py:347 pyanaconda/rescue.py:351 pyanaconda/text.py:526
#: pyanaconda/text.py:528
msgid "Exit"
msgstr ""

#: pyanaconda/rescue.py:365 pyanaconda/rescue.py:450
msgid "The system will reboot automatically when you exit from the shell."
msgstr ""

#: pyanaconda/rescue.py:376
#, python-format
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions. %s"
msgstr ""

#: pyanaconda/rescue.py:386
#, python-format
msgid ""
"Your system has been mounted under %(rootPath)s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"
msgstr ""

#: pyanaconda/rescue.py:457
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell."
msgstr ""

#: pyanaconda/rescue.py:466
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr ""

#: pyanaconda/rescue.py:470
msgid " The system will reboot automatically when you exit from the shell."
msgstr ""

#: pyanaconda/rescue.py:474
msgid "Rescue Mode"
msgstr ""

#: pyanaconda/rescue.py:475
#, python-format
msgid "You don't have any Linux partitions. Press return to get a shell.%s"
msgstr ""

#: pyanaconda/rescue.py:487
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr ""

#: pyanaconda/text.py:151
msgid "Passphrase for encrypted device"
msgstr ""

#: pyanaconda/text.py:164
msgid "Also add this passphrase to all existing encrypted devices"
msgstr ""

#: pyanaconda/text.py:195
#, python-format
msgid "The passphrase must be at least %d character long."
msgid_plural "The passphrase must be at least %d characters long."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/text.py:229 data/ui/lukspassphrase.glade.h:6
msgid "Passphrase"
msgstr ""

#: pyanaconda/text.py:265
msgid "Yes, discard any data"
msgstr ""

#: pyanaconda/text.py:266
msgid "No, keep any data"
msgstr ""

#: pyanaconda/text.py:376
msgid "Repository editing is not available in text mode."
msgstr ""

#: pyanaconda/text.py:445
#, python-format
msgid "Welcome to %(productName)s for %(productArch)s"
msgstr ""

#: pyanaconda/text.py:447
#, python-format
msgid "Welcome to %s"
msgstr ""

#: pyanaconda/text.py:449
msgid ""
"  <Tab>/<Alt-Tab> between elements   |  <Space> selects   |  <F12> next "
"screen"
msgstr ""

#: pyanaconda/text.py:526 pyanaconda/textw/constants_text.py:68
msgid "Retry"
msgstr ""

#: pyanaconda/text.py:542
msgid "Cancelled"
msgstr ""

#: pyanaconda/text.py:543
msgid "I can't go to the previous step from here. You will have to try again."
msgstr ""

#: pyanaconda/upgrade.py:51
msgid "Proceed with upgrade?"
msgstr ""

#: pyanaconda/upgrade.py:52
msgid ""
"The file systems of the Linux installation you have chosen to upgrade have "
"already been mounted. You cannot go back past this point. \n"
"\n"
msgstr ""

#: pyanaconda/upgrade.py:56
msgid "Would you like to continue with the upgrade?"
msgstr ""

#: pyanaconda/upgrade.py:87
#, python-format
msgid "Unknown release on %s -"
msgstr ""

#: pyanaconda/upgrade.py:92
msgid " Product mismatch."
msgstr ""

#: pyanaconda/upgrade.py:94
msgid " Version mismatch."
msgstr ""

#: pyanaconda/upgrade.py:96
msgid " Architecture mismatch."
msgstr ""

#: pyanaconda/upgrade.py:98
msgid "Cannot Upgrade"
msgstr ""

#: pyanaconda/upgrade.py:99
#, python-format
msgid ""
"Your current installation cannot be upgraded. This is likely due to it being "
"too old. Only the previous two releases may be upgraded. To upgrade older "
"releases you must first upgrade through all intermediate releases.\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/upgrade.py:181
msgid "Mount failed"
msgstr ""

#: pyanaconda/upgrade.py:182
#, python-format
msgid ""
"The following error occurred when mounting the file systems listed in /etc/"
"fstab.  Please fix this problem and try to upgrade again.\n"
"%s"
msgstr ""

#: pyanaconda/upgrade.py:190 pyanaconda/upgrade.py:197
msgid "Upgrade root not found"
msgstr ""

#: pyanaconda/upgrade.py:191
msgid "The root for the previously installed system was not found."
msgstr ""

#: pyanaconda/upgrade.py:198
msgid ""
"The root for the previously installed system was not found.  You can exit "
"installer or backtrack to choose installation instead of upgrade."
msgstr ""

#: pyanaconda/upgrade.py:221
msgid ""
"The following files are absolute symbolic links, which we do not support "
"during an upgrade. Please change them to relative symbolic links and restart "
"the upgrade.\n"
"\n"
msgstr ""

#: pyanaconda/upgrade.py:227
msgid "Absolute Symlinks"
msgstr ""

#: pyanaconda/upgrade.py:238
msgid ""
"The following are directories which should instead be symbolic links, which "
"will cause problems with the upgrade.  Please return them to their original "
"state as symbolic links and restart the upgrade.\n"
"\n"
msgstr ""

#: pyanaconda/upgrade.py:244
msgid "Invalid Directories"
msgstr ""

#: pyanaconda/upgrade.py:278
msgid "Upgrade /usr symlinks"
msgstr ""

#: pyanaconda/upgrade.py:279
msgid "Running /usr merge script"
msgstr ""

#: pyanaconda/upgrade.py:288
msgid "/usr merge failed"
msgstr ""

#: pyanaconda/upgrade.py:289
msgid ""
"The /usr merge script failed. This is required for Fedora 17 to work. The "
"upgrade cannot continue.\n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:125
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr ""

#: pyanaconda/vnc.py:131
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr ""

#: pyanaconda/vnc.py:148
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr ""

#: pyanaconda/vnc.py:162
msgid "Connected!"
msgstr ""

#: pyanaconda/vnc.py:165
msgid "Will try to connect again in 15 seconds..."
msgstr ""

#: pyanaconda/vnc.py:171
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/vnc.py:182
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""

#: pyanaconda/vnc.py:184
msgid "Please manually connect your vnc client to begin the install."
msgstr ""

#: pyanaconda/vnc.py:187
msgid "Starting VNC..."
msgstr ""

#: pyanaconda/vnc.py:224
msgid "The VNC server is now running."
msgstr ""

#: pyanaconda/vnc.py:228
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:233
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:237
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:239
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""

#: pyanaconda/vnc.py:261 pyanaconda/vnc.py:354
msgid "VNC Configuration"
msgstr ""

#: pyanaconda/vnc.py:264 pyanaconda/vnc.py:358
msgid "No password"
msgstr ""

#: pyanaconda/vnc.py:266 pyanaconda/vnc.py:361
msgid ""
"A password will prevent unauthorized listeners connecting and monitoring "
"your installation progress.  Please enter a password to be used for the "
"installation"
msgstr ""

#: pyanaconda/vnc.py:274 pyanaconda/vnc.py:369
#: pyanaconda/textw/userauth_text.py:47
msgid "Password:"
msgstr ""

#: pyanaconda/vnc.py:275 pyanaconda/vnc.py:370
#: pyanaconda/textw/userauth_text.py:49
msgid "Password (confirm):"
msgstr ""

#: pyanaconda/vnc.py:293 pyanaconda/vnc.py:392
#: pyanaconda/textw/userauth_text.py:70
msgid "Password Mismatch"
msgstr ""

#: pyanaconda/vnc.py:294 pyanaconda/vnc.py:393
#: pyanaconda/textw/userauth_text.py:71
msgid "The passwords you entered were different. Please try again."
msgstr ""

#: pyanaconda/vnc.py:299 pyanaconda/vnc.py:398
#: pyanaconda/textw/userauth_text.py:66
msgid "Password Length"
msgstr ""

#: pyanaconda/vnc.py:300 pyanaconda/vnc.py:399
msgid "The password must be at least six characters long."
msgstr ""

#: pyanaconda/vnc.py:322
msgid "Unable to Start X"
msgstr ""

#: pyanaconda/vnc.py:324
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""

#: pyanaconda/vnc.py:343
msgid "Start VNC"
msgstr ""

#: pyanaconda/vnc.py:344 pyanaconda/vnc.py:346
msgid "Use text mode"
msgstr ""

#: pyanaconda/yuminstall.py:86
#, python-format
msgid "%s MB"
msgstr ""

#: pyanaconda/yuminstall.py:89
#, python-format
msgid "%s KB"
msgstr ""

#: pyanaconda/yuminstall.py:91
#, python-format
msgid "%s Byte"
msgid_plural "%s Bytes"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/yuminstall.py:133
msgid "Preparing to install"
msgstr ""

#: pyanaconda/yuminstall.py:134
msgid "Preparing transaction from installation source"
msgstr ""

#: pyanaconda/yuminstall.py:169
#, python-format
msgid "<b>Upgrading %(pkgStr)s</b> (%(size)s)\n"
msgstr ""

#: pyanaconda/yuminstall.py:172
#, python-format
msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
msgstr ""

#: pyanaconda/yuminstall.py:217
#, python-format
msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/yuminstall.py:231
#, python-format
msgid "<b>Cleaning up %s</b>"
msgstr ""

#: pyanaconda/yuminstall.py:251
msgid "cpio"
msgstr ""

#: pyanaconda/yuminstall.py:253
msgid "unpack"
msgstr ""

#: pyanaconda/yuminstall.py:255
msgid "script"
msgstr ""

#: pyanaconda/yuminstall.py:256
msgid "Error Installing Package"
msgstr ""

#: pyanaconda/yuminstall.py:257
#, python-format
msgid ""
"A %s error occurred when installing the %s package.  This could indicate "
"errors when reading the installation media.  Installation cannot continue."
msgstr ""

#: pyanaconda/yuminstall.py:405
msgid "Wrong Disc"
msgstr ""

#: pyanaconda/yuminstall.py:406
#, python-format
msgid "That's not the correct %s disc."
msgstr ""

#: pyanaconda/yuminstall.py:559
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr ""

#: pyanaconda/yuminstall.py:826 pyanaconda/yuminstall.py:1260
#: pyanaconda/iw/task_gui.py:310
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""

#: pyanaconda/yuminstall.py:914 pyanaconda/yuminstall.py:916
msgid "Re_boot"
msgstr ""

#: pyanaconda/yuminstall.py:914
msgid "_Eject"
msgstr ""

#: pyanaconda/yuminstall.py:920
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""

#: pyanaconda/yuminstall.py:967
msgid "Retrying"
msgstr ""

#: pyanaconda/yuminstall.py:967
msgid "Retrying download."
msgstr ""

#: pyanaconda/yuminstall.py:1002
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr ""

#: pyanaconda/yuminstall.py:1046
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s.\n"
msgstr ""

#: pyanaconda/yuminstall.py:1048 pyanaconda/yuminstall.py:1100
#: pyanaconda/yuminstall.py:1105
msgid "Error Running Transaction"
msgstr ""

#: pyanaconda/yuminstall.py:1054 pyanaconda/yuminstall.py:1055
msgid "file conflicts"
msgstr ""

#: pyanaconda/yuminstall.py:1056
msgid "older package(s)"
msgstr ""

#: pyanaconda/yuminstall.py:1057
msgid "insufficient disk space"
msgstr ""

#: pyanaconda/yuminstall.py:1058
msgid "insufficient disk inodes"
msgstr ""

#: pyanaconda/yuminstall.py:1059
msgid "package conflicts"
msgstr ""

#: pyanaconda/yuminstall.py:1060
msgid "package already installed"
msgstr ""

#: pyanaconda/yuminstall.py:1061
msgid "required package"
msgstr ""

#: pyanaconda/yuminstall.py:1062
msgid "package for incorrect arch"
msgstr ""

#: pyanaconda/yuminstall.py:1063
msgid "package for incorrect os"
msgstr ""

#: pyanaconda/yuminstall.py:1077
msgid "You need more space on the following file systems:\n"
msgstr ""

#: pyanaconda/yuminstall.py:1090
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""

#: pyanaconda/yuminstall.py:1093
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): %"
"s.\n"
msgstr ""

#: pyanaconda/yuminstall.py:1285
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""

#: pyanaconda/yuminstall.py:1334 pyanaconda/textw/constants_text.py:64
msgid "Edit"
msgstr ""

#: pyanaconda/yuminstall.py:1345 pyanaconda/yuminstall.py:1552
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/yuminstall.py:1529
msgid ""
"Some of the packages you have selected for install are missing "
"dependencies.  You can exit the installation, go back and change your "
"package selections, or continue installing these packages without their "
"dependencies.  If you continue, these packages may not work correctly due to "
"missing components."
msgstr ""

#: pyanaconda/yuminstall.py:1574
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""

#: pyanaconda/yuminstall.py:1660
msgid "Post Upgrade"
msgstr ""

#: pyanaconda/yuminstall.py:1661
msgid "Performing post-upgrade configuration"
msgstr ""

#: pyanaconda/yuminstall.py:1663
msgid "Post Installation"
msgstr ""

#: pyanaconda/yuminstall.py:1664
msgid "Performing post-installation configuration"
msgstr ""

#: pyanaconda/yuminstall.py:1907
msgid "Installation Starting"
msgstr ""

#: pyanaconda/yuminstall.py:1908
msgid "Starting installation process"
msgstr ""

#: pyanaconda/yuminstall.py:1946
msgid "Dependency Check"
msgstr ""

#: pyanaconda/yuminstall.py:1947
msgid "Checking dependencies in packages selected for installation"
msgstr ""

#: pyanaconda/yuminstall.py:2003 pyanaconda/yuminstall.py:2019
msgid "Retrieving installation information."
msgstr ""

#: pyanaconda/yuminstall.py:2005 pyanaconda/yuminstall.py:2021
#, python-format
msgid "Retrieving installation information for %s."
msgstr ""

#: pyanaconda/yuminstall.py:2006 pyanaconda/yuminstall.py:2022
msgid "Installation Progress"
msgstr ""

#: pyanaconda/installclasses/fedora.py:41
msgid "_Fedora"
msgstr ""

#: pyanaconda/installclasses/fedora.py:42
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. You can optionally select a different set of "
"software now."
msgstr ""

#: pyanaconda/installclasses/fedora.py:51
msgid "Graphical Desktop"
msgstr ""

#: pyanaconda/installclasses/fedora.py:56
msgid "Software Development"
msgstr ""

#: pyanaconda/installclasses/fedora.py:62
msgid "Web Server"
msgstr ""

#: pyanaconda/installclasses/fedora.py:66 pyanaconda/installclasses/rhel.py:44
msgid "Minimal"
msgstr ""

#: pyanaconda/installclasses/rhel.py:33
msgid "Red Hat Enterprise Linux"
msgstr ""

#: pyanaconda/installclasses/rhel.py:34
#, python-format
msgid ""
"The default installation of %s is a minimum install. You can optionally "
"select a different set of software now."
msgstr ""

#: pyanaconda/iw/GroupSelector.py:147
#, python-format
msgid "Packages in %s"
msgstr ""

#: pyanaconda/iw/GroupSelector.py:433
#, python-format
msgid "Optional packages selected: %(inst)d of %(cnt)d"
msgstr ""

#: pyanaconda/iw/GroupSelector.py:435
#, python-format
msgid "<i>%s</i>"
msgstr ""

#: pyanaconda/iw/GroupSelector.py:495
msgid "Uncategorized"
msgstr ""

#: pyanaconda/iw/account_gui.py:52
msgid "Root _Password:"
msgstr ""

#: pyanaconda/iw/account_gui.py:54
msgid "_Confirm:"
msgstr ""

#: pyanaconda/iw/account_gui.py:92
msgid "Caps Lock is on."
msgstr ""

#: pyanaconda/iw/account_gui.py:102 pyanaconda/iw/account_gui.py:110
#: pyanaconda/iw/account_gui.py:117 pyanaconda/iw/account_gui.py:139
#: pyanaconda/textw/userauth_text.py:74
msgid "Error with Password"
msgstr ""

#: pyanaconda/iw/account_gui.py:103
msgid ""
"You must enter your root password and confirm it by typing it a second time "
"to continue."
msgstr ""

#: pyanaconda/iw/account_gui.py:111
msgid "The passwords you entered were different.  Please try again."
msgstr ""

#: pyanaconda/iw/account_gui.py:118
msgid "The root password must be at least six characters long."
msgstr ""

#: pyanaconda/iw/account_gui.py:128 pyanaconda/textw/userauth_text.py:84
msgid "Weak Password"
msgstr ""

#: pyanaconda/iw/account_gui.py:129
#, python-format
msgid "You have provided a weak password: %s"
msgstr ""

#: pyanaconda/iw/account_gui.py:132
msgid "_Use Anyway"
msgstr ""

#: pyanaconda/iw/account_gui.py:140 pyanaconda/textw/userauth_text.py:75
msgid ""
"Requested password contains non-ASCII characters, which are not allowed."
msgstr ""

#: pyanaconda/iw/advanced_storage.py:256
msgid "Node Name"
msgstr ""

#: pyanaconda/iw/advanced_storage.py:379
msgid "You must select a NIC to use."
msgstr ""

#: pyanaconda/iw/autopart_type.py:96
msgid ""
"No partitions are available to resize.  Only physical partitions with "
"specific filesystems can be resized."
msgstr ""

#: pyanaconda/iw/autopart_type.py:121
msgid "Resize FileSystem Error"
msgstr ""

#: pyanaconda/iw/autopart_type.py:122
#, python-format
msgid "%(device)s: %(msg)s"
msgstr ""

#: pyanaconda/iw/autopart_type.py:131
msgid "Resize Device Error"
msgstr ""

#: pyanaconda/iw/autopart_type.py:132
#, python-format
msgid "%(name)s: %(msg)s"
msgstr ""

#: pyanaconda/iw/autopart_type.py:269
msgid "Use _All Space"
msgstr ""

#: pyanaconda/iw/autopart_type.py:271
msgid ""
"Removes all partitions on the selected device(s).  This includes partitions "
"created by other operating systems.\n"
"\n"
"<b>Tip:</b> This option will remove data from the selected device(s).  Make "
"sure you have backups."
msgstr ""

#: pyanaconda/iw/autopart_type.py:277
msgid "Replace Existing _Linux System(s)"
msgstr ""

#: pyanaconda/iw/autopart_type.py:279
msgid ""
"Removes all Linux partitions on the selected device(s). This does not remove "
"other partitions you may have on your storage device(s) (such as VFAT or "
"FAT32).\n"
"\n"
"<b>Tip:</b> This option will remove data from the selected device(s).  Make "
"sure you have backups."
msgstr ""

#: pyanaconda/iw/autopart_type.py:287
msgid "_Shrink Current System"
msgstr ""

#: pyanaconda/iw/autopart_type.py:289
msgid ""
"Shrinks existing partitions to create free space for the default layout."
msgstr ""

#: pyanaconda/iw/autopart_type.py:291
msgid "Use _Free Space"
msgstr ""

#: pyanaconda/iw/autopart_type.py:293
msgid ""
"Retains your current data and partitions and uses only the unpartitioned "
"space on the selected device(s), assuming you have enough free space "
"available."
msgstr ""

#: pyanaconda/iw/autopart_type.py:297
msgid "Create _Custom Layout"
msgstr ""

#: pyanaconda/iw/autopart_type.py:299
msgid ""
"Manually create your own custom layout on the selected device(s) using our "
"partitioning tool."
msgstr ""

#: pyanaconda/iw/blpasswidget.py:43
msgid "_Use a boot loader password"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:44
msgid ""
"A boot loader password prevents users from changing kernel options, "
"increasing security."
msgstr ""

#: pyanaconda/iw/blpasswidget.py:71
msgid "Change _password"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:94
msgid "Enter Boot Loader Password"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:100
msgid ""
"Enter a boot loader password and then confirm it.  (Note that your BIOS "
"keymap may be different than the actual keymap you are used to.)"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:107
msgid "_Password:"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:113
msgid "Con_firm:"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:135
msgid "Passwords don't match"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:136
msgid "Passwords do not match"
msgstr ""

#: pyanaconda/iw/blpasswidget.py:145
msgid ""
"Your boot loader password is shorter than six characters.  We recommend a "
"longer boot loader password.\n"
"\n"
"Would you like to continue with this password?"
msgstr ""

#: pyanaconda/iw/bootloader_main_gui.py:36
msgid "Boot Loader Configuration"
msgstr ""

#: pyanaconda/iw/bootloader_main_gui.py:167
#: pyanaconda/iw/bootloader_main_gui.py:184
#, python-format
msgid "_Install boot loader on %s."
msgstr ""

#: pyanaconda/iw/bootloader_main_gui.py:194
msgid "_Change device"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:34
msgid "Clear Disks Selector"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:45 pyanaconda/iw/filter_gui.py:444
msgid "You must select at least one drive to be used for installation."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:55
msgid "You must select one drive to boot from."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:132 pyanaconda/iw/cleardisks_gui.py:152
#: pyanaconda/iw/filter_gui.py:506 pyanaconda/iw/filter_gui.py:517
#: pyanaconda/iw/filter_gui.py:547
msgid "Model"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:133 pyanaconda/iw/cleardisks_gui.py:153
msgid "Capacity"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:134 pyanaconda/iw/filter_gui.py:508
#: pyanaconda/iw/filter_gui.py:527 pyanaconda/iw/filter_gui.py:538
#: pyanaconda/iw/filter_gui.py:549
msgid "Vendor"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:135 pyanaconda/iw/cleardisks_gui.py:154
#: pyanaconda/iw/filter_gui.py:525 pyanaconda/iw/filter_gui.py:536
#: pyanaconda/iw/filter_gui.py:552
msgid "Identifier"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:136 pyanaconda/iw/filter_gui.py:509
#: pyanaconda/iw/filter_gui.py:528 pyanaconda/iw/filter_gui.py:539
#: pyanaconda/iw/filter_gui.py:550
msgid "Interconnect"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:150
msgid ""
"Boot\n"
"Loader"
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:208
msgid ""
"<b>Tip:</b> All Linux filesystems on the install target devices will be "
"reformatted and wiped of any data.  Make sure you have backups."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:210
msgid ""
"<b>Tip:</b> The install target devices will be reformatted and wiped of any "
"data.  Make sure you have backups."
msgstr ""

#: pyanaconda/iw/cleardisks_gui.py:212
msgid ""
"<b>Tip:</b> Your filesystems on the install target devices will not be "
"reformatted unless you choose to do so during customization."
msgstr ""

#: pyanaconda/iw/congrats_gui.py:34
msgid "Congratulations"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:75 pyanaconda/textw/complete_text.py:39
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:78 pyanaconda/textw/complete_text.py:42
msgid "Shutdown"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:80 pyanaconda/textw/complete_text.py:44
msgid "Please shutdown to use the installed system.\n"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:82 pyanaconda/textw/complete_text.py:46
msgid "Please reboot to use the installed system.\n"
msgstr ""

#: pyanaconda/iw/congrats_gui.py:87 pyanaconda/textw/complete_text.py:51
msgid ""
"Note that updates may be available to ensure the proper functioning of your "
"system and installation of these updates is recommended after the reboot."
msgstr ""

#: pyanaconda/iw/congrats_gui.py:91 pyanaconda/textw/complete_text.py:55
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
"Please reboot to use the installed system.  Note that updates may be "
"available to ensure the proper functioning of your system and installation "
"of these updates is recommended after the reboot."
msgstr ""

#: pyanaconda/iw/examine_gui.py:39
msgid "Upgrade Examine"
msgstr ""

#: pyanaconda/iw/examine_gui.py:59
msgid "Fresh Installation"
msgstr ""

#: pyanaconda/iw/examine_gui.py:61
#, python-format
msgid ""
"Choose this option to install a fresh copy of %s on your system.  Existing "
"software and data may be overwritten depending on your configuration choices."
msgstr ""

#: pyanaconda/iw/examine_gui.py:66
msgid "Upgrade an Existing Installation"
msgstr ""

#: pyanaconda/iw/examine_gui.py:68
#, python-format
msgid ""
"Choose this option if you would like to upgrade your existing %s system.  "
"This option will preserve the existing data on your storage device(s)."
msgstr ""

#: pyanaconda/iw/examine_gui.py:118
msgid ""
"At least one existing installation has been detected on your system.  What "
"would you like to do?"
msgstr ""

#: pyanaconda/iw/examine_gui.py:137
#, python-format
msgid "<b>Which %s installation would you like to upgrade?</b>"
msgstr ""

#: pyanaconda/iw/examine_gui.py:151
msgid "Unknown Linux system"
msgstr ""

#: pyanaconda/iw/filter_gui.py:151
#, python-format
msgid ""
"Selected devices: %(selectedDevices)s (%(selectedSize)s MB) out of %"
"(totalDevices)s (%(totalSize)s MB)."
msgstr ""

#: pyanaconda/iw/filter_gui.py:401
msgid "Device Filter"
msgstr ""

#: pyanaconda/iw/filter_gui.py:507 pyanaconda/iw/filter_gui.py:518
#: pyanaconda/iw/filter_gui.py:526 pyanaconda/iw/filter_gui.py:537
#: pyanaconda/iw/filter_gui.py:548
msgid "Capacity (MB)"
msgstr ""

#: pyanaconda/iw/filter_gui.py:510 pyanaconda/iw/filter_gui.py:540
#: pyanaconda/iw/filter_gui.py:551
msgid "Serial Number"
msgstr ""

#: pyanaconda/iw/filter_gui.py:511 pyanaconda/iw/filter_gui.py:519
#: pyanaconda/iw/filter_gui.py:530 pyanaconda/iw/filter_gui.py:541
#: pyanaconda/iw/filter_gui.py:556 pyanaconda/iw/osbootwidget.py:64
#: pyanaconda/iw/partition_gui.py:600
msgid "Device"
msgstr ""

#: pyanaconda/iw/filter_gui.py:529
msgid "Paths"
msgstr ""

#: pyanaconda/iw/filter_gui.py:553
msgid "Port"
msgstr ""

#: pyanaconda/iw/filter_gui.py:554
msgid "Target"
msgstr ""

#: pyanaconda/iw/filter_gui.py:555
msgid "LUN"
msgstr ""

#: pyanaconda/iw/filter_type.py:59
msgid "What type of devices will your installation involve?"
msgstr ""

#: pyanaconda/iw/filter_type.py:65
msgid "B_asic Storage Devices"
msgstr ""

#: pyanaconda/iw/filter_type.py:66
msgid ""
"Installs or upgrades to typical types of storage devices.  If you're not "
"sure which option is right for you, this is probably it."
msgstr ""

#: pyanaconda/iw/filter_type.py:70
msgid "_Specialized Storage Devices"
msgstr ""

#: pyanaconda/iw/filter_type.py:71
msgid ""
"Installs or upgrades to enterprise devices such as Storage Area Networks "
"(SANs). This option will allow you to add FCoE / iSCSI / zFCP disks and to "
"filter out devices the installer should ignore."
msgstr ""

#: pyanaconda/iw/language_gui.py:33 pyanaconda/textw/language_text.py:45
msgid "Language Selection"
msgstr ""

#: pyanaconda/iw/language_gui.py:82 pyanaconda/textw/language_text.py:46
msgid "What language would you like to use during the installation process?"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:134 pyanaconda/iw/lvm_dialog_gui.py:180
#: pyanaconda/iw/lvm_dialog_gui.py:194 pyanaconda/iw/lvm_dialog_gui.py:233
#: pyanaconda/iw/lvm_dialog_gui.py:311 pyanaconda/iw/lvm_dialog_gui.py:708
#: pyanaconda/iw/lvm_dialog_gui.py:729
msgid "Not enough space"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:135
msgid ""
"The physical extent size cannot be changed because otherwise the space "
"required by the currently defined logical volumes will be increased to more "
"than the available space."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:144
msgid "Confirm Physical Extent Change"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:145
msgid ""
"This change in the value of the physical extent will require the sizes of "
"the current logical volume requests to be rounded up in size to an integer "
"multiple of the physical extent.\n"
"\n"
"This change will take effect immediately."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:154 pyanaconda/iw/lvm_dialog_gui.py:216
msgid "C_ontinue"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:181
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected (%"
"(curpe)10.2f MB) is larger than the smallest physical volume (%(maxpvsize)"
"10.2f MB) in the volume group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:195
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected (%"
"(curpe)10.2f MB) is too large compared to the size of the smallest physical "
"volume (%(maxpvsize)10.2f MB) in the volume group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:209
msgid "Too small"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:210
msgid ""
"This change in the value of the physical extent will waste substantial space "
"on one or more of the physical volumes in the volume group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:234
#, python-format
msgid ""
"The physical extent size cannot be changed because the resulting maximum "
"logical volume size (%10.2f MB) is smaller than one or more of the currently "
"defined logical volumes."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:312
msgid ""
"You cannot remove this physical volume because otherwise the volume group "
"will be too small to hold the currently defined logical volumes."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:412
msgid "Make Logical Volume"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:414
#, python-format
msgid "Edit Logical Volume: %s"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:453 pyanaconda/iw/raid_dialog_gui.py:453
msgid "_File System Type:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:459
msgid "_Logical Volume Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:469
#: pyanaconda/iw/partition_dialog_gui.py:510
msgid "_Size (MB):"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:476
#, python-format
msgid "(Max size is %s MB)"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:481
#: pyanaconda/iw/partition_dialog_gui.py:562
#: pyanaconda/iw/partition_ui_helpers_gui.py:337
#: pyanaconda/iw/raid_dialog_gui.py:425
msgid "_Encrypt"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:490
#: pyanaconda/iw/partition_dialog_gui.py:492
#: pyanaconda/iw/raid_dialog_gui.py:463
msgid "Original File System Type:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:495
#: pyanaconda/iw/partition_dialog_gui.py:500
#: pyanaconda/iw/raid_dialog_gui.py:470
msgid "Original File System Label:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:500
msgid "Logical Volume Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:504
msgid "Size (MB):"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:531
#: pyanaconda/iw/partition_dialog_gui.py:443
#: pyanaconda/iw/raid_dialog_gui.py:444
msgid "_Mount Point:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:612
#: pyanaconda/iw/partition_dialog_gui.py:118
#: pyanaconda/iw/raid_dialog_gui.py:172
msgid "Mount Point Error"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:622
msgid "Illegal Logical Volume Name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:637
msgid "Illegal logical volume name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:638
#, python-format
msgid "The logical volume name \"%s\" is already in use. Please pick another."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:679
#: pyanaconda/iw/partition_dialog_gui.py:134
#: pyanaconda/iw/raid_dialog_gui.py:187
msgid "Mount point in use"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:680
#: pyanaconda/iw/partition_dialog_gui.py:135
#: pyanaconda/iw/raid_dialog_gui.py:188
#, python-format
msgid "The mount point \"%s\" is in use. Please pick another."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:695
msgid "Illegal size"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:696
msgid "The requested size as entered is not a valid number greater than 0."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:709
#, python-format
msgid ""
"The current requested size (%(size)10.2f MB) is larger than the maximum "
"logical volume size (%(maxlv)10.2f MB). To increase this limit you can "
"create more Physical Volumes from unpartitioned disk space and add them to "
"this Volume Group."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:730
#, python-format
msgid ""
"The size entered for this logical volume (%(size)d MB) combined with the "
"size of the other logical volume(s) exceeds the size of the volume group (%"
"(tempvgsize)d MB). Please make the volume group larger or make the logical "
"volume smaller."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:850
msgid "No free slots"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:851
#, python-format
msgid "You cannot create more than %d logical volume per volume group."
msgid_plural "You cannot create more than %d logical volumes per volume group."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/iw/lvm_dialog_gui.py:861
msgid "No free space"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:862
msgid ""
"There is no room left in the volume group to create new logical volumes. To "
"add a logical volume you must reduce the size of one or more of the "
"currently existing logical volumes"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:899
#, python-format
msgid "Are you sure you want to delete the logical volume \"%s\"?"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1023
msgid "Invalid Volume Group Name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1032
msgid "Name in use"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1033
#, python-format
msgid "The volume group name \"%s\" is already in use. Please pick another."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1132 pyanaconda/iw/partition_gui.py:1616
#: pyanaconda/storage/partitioning.py:313
#: pyanaconda/storage/partitioning.py:351
msgid "Error Partitioning"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1133
#, python-format
msgid ""
"Could not allocate requested logical volumes:\n"
"\n"
"%s."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1340
msgid "Not enough physical volumes"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1341
msgid ""
"At least one unused physical volume partition is needed to create an LVM "
"Volume Group.\n"
"\n"
"Create a partition or RAID array of type \"physical volume (LVM)\" and then "
"select the \"LVM\" option again."
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1352
msgid "Make LVM Volume Group"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1355
#, python-format
msgid "Edit LVM Volume Group: %s"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1357
msgid "Edit LVM Volume Group"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1373
msgid "_Volume Group Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1382
msgid "Volume Group Name:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1390
msgid "_Physical Extent:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1405
msgid "Physical Volumes to _Use:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1411
msgid "Used Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1429
msgid "Snapshot Total:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1450
msgid "Reserved Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1470
msgid "Free Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1488
msgid "Total Space:"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1526
msgid "Logical Volume Name"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1529 pyanaconda/iw/partition_gui.py:603
msgid "Mount Point"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1532 pyanaconda/iw/partition_gui.py:602
msgid "Size (MB)"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1546 pyanaconda/iw/osbootwidget.py:97
msgid "_Add"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1549 pyanaconda/iw/osbootwidget.py:101
#: pyanaconda/iw/partition_gui.py:1842 pyanaconda/iw/partition_gui.py:1852
msgid "_Edit"
msgstr ""

#: pyanaconda/iw/lvm_dialog_gui.py:1564
msgid "_Logical Volumes"
msgstr ""

#: pyanaconda/iw/network_gui.py:83 pyanaconda/iw/network_gui.py:89
msgid "Error with Hostname"
msgstr ""

#: pyanaconda/iw/network_gui.py:84
msgid "You must enter a valid hostname for this computer."
msgstr ""

#: pyanaconda/iw/network_gui.py:90
#, python-format
msgid ""
"The hostname \"%(hostname)s\" is not valid for the following reason:\n"
"\n"
"%(herrors)s"
msgstr ""

#: pyanaconda/iw/network_gui.py:134
msgid "Select network interface"
msgstr ""

#: pyanaconda/iw/network_gui.py:141
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please configure a network interface."
msgstr ""

#: pyanaconda/iw/network_gui.py:211
msgid "Select APs"
msgstr ""

#: pyanaconda/iw/network_gui.py:218
msgid "Select APs for wireless devices"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:49
msgid "Boot loader operating system list"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:64
msgid "Default"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:64 pyanaconda/iw/partition_gui.py:601
msgid "Label"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:131
msgid "Image"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:138
msgid ""
"Enter a label for the boot loader menu to display. The device (or hard drive "
"and partition number) is the device from which it boots."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:146
msgid "_Label"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:154
msgid "_Device"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:185
msgid "Default Boot _Target"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:210
msgid "You must select a device."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:216
msgid "You must specify a label for the entry"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:225
msgid "Boot label contains illegal characters"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:247
msgid "Duplicate Label"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:248
msgid "This label is already in use for another boot entry."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:259
msgid "Duplicate Device"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:260
msgid "This device is already being used for another boot entry."
msgstr ""

#: pyanaconda/iw/osbootwidget.py:308
msgid "Cannot Delete"
msgstr ""

#: pyanaconda/iw/osbootwidget.py:309
#, python-format
msgid ""
"This boot target cannot be deleted because it is for the %s system you are "
"about to install."
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:58
msgid "Additional Size Options"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:63
msgid "_Fixed size"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:65
msgid "Fill all space _up to (MB):"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:72
msgid "Fill to maximum _allowable size"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:193
msgid "Error With Request"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:413
msgid "Add Partition"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:415
#, python-format
msgid "Edit Partition: %s"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:452
msgid "File System _Type:"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:468
msgid "Allowable _Drives:"
msgstr ""

#: pyanaconda/iw/partition_dialog_gui.py:549
msgid "Force to be a _primary partition"
msgstr ""

#: pyanaconda/iw/partition_gui.py:361
#, python-format
msgid "Drive %(drive)s (%(size)-0.f MB) (Model: %(model)s)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:384 pyanaconda/iw/partition_gui.py:396
#: pyanaconda/iw/partition_gui.py:486 pyanaconda/iw/partition_gui.py:1012
#: pyanaconda/iw/partition_gui.py:1100
msgid "Free"
msgstr ""

#: pyanaconda/iw/partition_gui.py:451
#, python-format
msgid "LVM Volume Group %(vgName)s (%(vgSize)-0.f MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:518
#, python-format
msgid "%(desc)s %(mdPath)s (%(mdSize)-0.f MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:548
#, python-format
msgid "%(desc)s %(mdUUID)s (%(mdSize)-0.f MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:604
msgid "Type"
msgstr ""

#: pyanaconda/iw/partition_gui.py:605 pyanaconda/storage/__init__.py:2144
msgid "Format"
msgstr ""

#: pyanaconda/iw/partition_gui.py:642
msgid ""
"Mount Point/\n"
"RAID/Volume"
msgstr ""

#: pyanaconda/iw/partition_gui.py:644
msgid ""
"Size\n"
"(MB)"
msgstr ""

#: pyanaconda/iw/partition_gui.py:749
msgid "Partitioning"
msgstr ""

#: pyanaconda/iw/partition_gui.py:839
msgid ""
"The partitioning scheme you requested caused the following critical errors."
msgstr ""

#: pyanaconda/iw/partition_gui.py:841
#, python-format
msgid ""
"You must correct these errors before you continue your installation of %s."
msgstr ""

#: pyanaconda/iw/partition_gui.py:847
msgid "Partitioning Errors"
msgstr ""

#: pyanaconda/iw/partition_gui.py:854
msgid "The partitioning scheme you requested generated the following warnings."
msgstr ""

#: pyanaconda/iw/partition_gui.py:856
msgid "Would you like to continue with your requested partitioning scheme?"
msgstr ""

#: pyanaconda/iw/partition_gui.py:861
msgid "Partitioning Warnings"
msgstr ""

#: pyanaconda/iw/partition_gui.py:870
msgid ""
"The following pre-existing devices have been selected to be formatted, "
"destroying all data."
msgstr ""

#: pyanaconda/iw/partition_gui.py:882
msgid "Format Warnings"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1000
msgid "LVM Volume Groups"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1022
msgid "RAID Devices"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1034
msgid "BTRFS Volumes"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1047
msgid "Hard Drives"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1104
msgid "Extended"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1398
msgid "Cannot perform any creation action"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1399
msgid ""
"Note that the creation action requires one of the following:\n"
"\n"
"* Free space in one of the Hard Drives.\n"
"* At least two free Software RAID partitions.\n"
"* At least one free physical volume (LVM) partition.\n"
"* At least one Volume Group with free space."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1502
#, python-format
msgid ""
"Software RAID allows you to combine several disks into a larger RAID "
"device.  A RAID device can be configured to provide additional speed and "
"reliability compared to using an individual drive.  For more information on "
"using RAID devices please consult the %s documentation.\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1508
msgid ""
"To use RAID you must first create at least two partitions of type 'software "
"RAID'.  Then you can create a RAID device that can be formatted and "
"mounted.\n"
"\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1512
#, python-format
msgid "You currently have %d software RAID partition free to use."
msgid_plural "You currently have %d software RAID partitions free to use."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/iw/partition_gui.py:1516
msgid "About RAID"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1522
#, python-format
msgid ""
"Logical Volume Manager (LVM) is a 3 level construct. The first level is made "
"up of disks or partitions formatted with LVM metadata called Physical "
"Volumes (PV).  A Volume Group (VG) sits on top of one or more PVs. The VG, "
"in turn, is the base to create one or more Logical Volumes (LV).  Note that "
"a VG can be an aggregate of PVs from multiple physical disks.  For more "
"information on using LVM please consult the %s documentation\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1530
msgid ""
"To create a PV you need a partition with free space.  To create a VG you "
"need a PV that is not part of any existing VG.  To create an LV you need a "
"VG with free space.\n"
"\n"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1534
#, python-format
msgid "You currently have %d available PV free to use.\n"
msgid_plural "You currently have %d available PVs free to use.\n"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/iw/partition_gui.py:1538
msgid "About LVM"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1617
#, python-format
msgid "Could not allocate requested partitions: %s."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1626
#, python-format
msgid "Warning: %s."
msgstr ""

#: pyanaconda/iw/partition_gui.py:1657
msgid "Unable To Edit"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1658
#, python-format
msgid ""
"You cannot edit this device:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1841
msgid "_Create"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1844
msgid "Re_set"
msgstr ""

#: pyanaconda/iw/partition_gui.py:1867
msgid "Please Select A Device"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:110
#: pyanaconda/iw/partition_ui_helpers_gui.py:132
#: pyanaconda/iw/partition_ui_helpers_gui.py:134
msgid "<Not Applicable>"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:318
msgid "_Format as:"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:340
msgid "Mi_grate filesystem to:"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:370
msgid "_Resize"
msgstr ""

#: pyanaconda/iw/partition_ui_helpers_gui.py:425
#, python-format
msgid ""
"Partitions of type '%s' must be constrained to a single drive.  To do this, "
"select the drive in the 'Allowable Drives' checklist."
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:392
msgid ""
"At least two unused software RAID partitions are needed to create a RAID "
"device.\n"
"\n"
"First create at least two partitions of type \"software RAID\", and then "
"select the \"RAID\" option again."
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:406
msgid "Make RAID Device"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:409
#, python-format
msgid "Edit RAID Device: %s"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:411
msgid "Edit RAID Device"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:478
msgid "RAID _Device:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:496
msgid "RAID _Level:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:522
msgid "_RAID Members:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:539
msgid "Number of _spares:"
msgstr ""

#: pyanaconda/iw/raid_dialog_gui.py:549
msgid "_Format partition?"
msgstr ""

#: pyanaconda/iw/task_gui.py:52
#, python-format
msgid ""
"Unable to read package metadata from repository.  This may be due to a "
"missing repodata directory.  Please ensure that your repository has been "
"correctly generated.\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/iw/task_gui.py:126
msgid "Edit Repository"
msgstr ""

#: pyanaconda/iw/task_gui.py:152
#, python-format
msgid ""
"The repository %s has already been added.  Please choose a different "
"repository name and URL."
msgstr ""

#: pyanaconda/iw/task_gui.py:238
msgid "Invalid Proxy URL"
msgstr ""

#: pyanaconda/iw/task_gui.py:239
msgid "You must provide an HTTP, HTTPS, or FTP URL to a proxy."
msgstr ""

#: pyanaconda/iw/task_gui.py:251 pyanaconda/iw/task_gui.py:434
msgid "Invalid Repository URL"
msgstr ""

#: pyanaconda/iw/task_gui.py:252 pyanaconda/iw/task_gui.py:435
msgid "You must provide an HTTP, HTTPS, or FTP URL to a repository."
msgstr ""

#: pyanaconda/iw/task_gui.py:273 pyanaconda/iw/task_gui.py:444
msgid "No Media Found"
msgstr ""

#: pyanaconda/iw/task_gui.py:274 pyanaconda/iw/task_gui.py:445
msgid ""
"No installation media was found. Please insert a disc into your drive and "
"try again."
msgstr ""

#: pyanaconda/iw/task_gui.py:304 pyanaconda/iw/task_gui.py:467
msgid "Please enter an NFS server and path."
msgstr ""

#: pyanaconda/iw/task_gui.py:322
#, python-format
msgid ""
"The following error occurred while setting up the repository:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/iw/task_gui.py:345
msgid "Invalid Repository Name"
msgstr ""

#: pyanaconda/iw/task_gui.py:346
msgid "You must provide a repository name."
msgstr ""

#: pyanaconda/iw/task_gui.py:499 data/ui/addrepo.glade.h:3
msgid "Add Repository"
msgstr ""

#: pyanaconda/iw/task_gui.py:504
msgid "No Software Repos Enabled"
msgstr ""

#: pyanaconda/iw/task_gui.py:505
msgid ""
"You must have at least one software repository enabled to continue "
"installation."
msgstr ""

#: pyanaconda/iw/timezone_gui.py:52 pyanaconda/textw/timezone_text.py:66
msgid "Time Zone Selection"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:36
#: pyanaconda/textw/upgrade_bootloader_text.py:55
msgid "Upgrade Boot Loader Configuration"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:56
#: pyanaconda/textw/upgrade_bootloader_text.py:48
msgid "_Create new boot loader configuration"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:58
msgid ""
"This option creates a new boot loader configuration.  If you wish to switch "
"boot loaders, you should choose this."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:65
#: pyanaconda/textw/upgrade_bootloader_text.py:50
msgid "_Skip boot loader updating"
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:66
msgid ""
"This option makes no changes to boot loader configuration.  If you are using "
"a third party boot loader, you should choose this."
msgstr ""

#: pyanaconda/iw/upgrade_bootloader_gui.py:88
msgid "What would you like to do?"
msgstr ""

#: pyanaconda/iw/upgrade_migratefs_gui.py:38
#: pyanaconda/textw/upgrade_text.py:42
msgid "Migrate File Systems"
msgstr ""

#: pyanaconda/iw/upgrade_migratefs_gui.py:69
#: pyanaconda/textw/upgrade_text.py:44
#, python-format
msgid ""
"This release of %(productName)s supports an updated file system, which has "
"several benefits over the file system traditionally shipped in %(productName)"
"s.  This installation program can migrate formatted partitions without data "
"loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""

#: pyanaconda/iw/zipl_gui.py:37
msgid "z/IPL Boot Loader Configuration"
msgstr ""

#: pyanaconda/iw/zipl_gui.py:56
msgid "The z/IPL boot loader will be installed on your system."
msgstr ""

#: pyanaconda/iw/zipl_gui.py:58
msgid ""
"The z/IPL Boot Loader will now be installed on your system.\n"
"\n"
"The root partition will be the one you selected previously in the partition "
"setup.\n"
"\n"
"The kernel used to start the machine will be the one to be installed by "
"default.\n"
"\n"
"If you wish to make changes later after the installation feel free to change "
"the /etc/zipl.conf configuration file.\n"
"\n"
"You can now enter any additional kernel parameters which your machine or "
"your setup may require."
msgstr ""

#: pyanaconda/iw/zipl_gui.py:85 pyanaconda/textw/zipl_text.py:54
msgid "Kernel Parameters"
msgstr ""

#: pyanaconda/storage/__init__.py:95
msgid "Unknown Device"
msgstr ""

#: pyanaconda/storage/__init__.py:96
#, python-format
msgid ""
"The installation source given by device %s could not be found.  Please check "
"your parameters and try again."
msgstr ""

#: pyanaconda/storage/__init__.py:105
msgid "_Try again"
msgstr ""

#: pyanaconda/storage/__init__.py:108
msgid "No disks found"
msgstr ""

#: pyanaconda/storage/__init__.py:109
msgid "No usable disks have been found."
msgstr ""

#: pyanaconda/storage/__init__.py:122
msgid "Installation cannot continue."
msgstr ""

#: pyanaconda/storage/__init__.py:123
msgid ""
"The storage configuration you have chosen has already been activated. You "
"can no longer return to the disk editing screen. Would you like to continue "
"with the installation process?"
msgstr ""

#: pyanaconda/storage/__init__.py:151
msgid "Encrypt device?"
msgstr ""

#: pyanaconda/storage/__init__.py:152
msgid ""
"You specified block device encryption should be enabled, but you have not "
"supplied a passphrase. If you do not go back and provide a passphrase, block "
"device encryption will be disabled."
msgstr ""

#: pyanaconda/storage/__init__.py:159 pyanaconda/storage/devicetree.py:94
#: pyanaconda/textw/constants_text.py:52
msgid "Back"
msgstr ""

#: pyanaconda/storage/__init__.py:190
msgid "Missing /boot Volume"
msgstr ""

#: pyanaconda/storage/__init__.py:191
msgid ""
"This platform requires /boot on a dedicated partition or logical volume.  If "
"you do not want a /boot volume, you must place / on a dedicated non-LVM "
"partition."
msgstr ""

#: pyanaconda/storage/__init__.py:198
msgid "Go _back"
msgstr ""

#: pyanaconda/storage/__init__.py:205 pyanaconda/storage/devicetree.py:103
msgid "Confirm"
msgstr ""

#: pyanaconda/storage/__init__.py:206
msgid ""
"The partitioning options you have selected will now be written to disk.  Any "
"data on deleted or reformatted partitions will be lost."
msgstr ""

#: pyanaconda/storage/__init__.py:211
msgid "Go _Back"
msgstr ""

#: pyanaconda/storage/__init__.py:212
msgid "_Write Changes to Disk"
msgstr ""

#: pyanaconda/storage/__init__.py:231
msgid "Running..."
msgstr ""

#: pyanaconda/storage/__init__.py:232
msgid "Storing encryption keys"
msgstr ""

#: pyanaconda/storage/__init__.py:248
#, python-format
msgid "Error storing an encryption key: %s\n"
msgstr ""

#: pyanaconda/storage/__init__.py:459
msgid "Examining Devices"
msgstr ""

#: pyanaconda/storage/__init__.py:460
msgid "Examining storage devices"
msgstr ""

#: pyanaconda/storage/__init__.py:780
msgid "This partition is holding the data for the hard drive install."
msgstr ""

#: pyanaconda/storage/__init__.py:785
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr ""

#: pyanaconda/storage/__init__.py:791
#, python-format
msgid "This device is part of the RAID device %s."
msgstr ""

#: pyanaconda/storage/__init__.py:794
msgid "This device is part of a RAID device."
msgstr ""

#: pyanaconda/storage/__init__.py:797
msgid "This device is part of an inconsistent LVM Volume Group."
msgstr ""

#: pyanaconda/storage/__init__.py:802
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr ""

#: pyanaconda/storage/__init__.py:805
msgid "This device is part of a LVM volume group."
msgstr ""

#: pyanaconda/storage/__init__.py:821
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""

#: pyanaconda/storage/__init__.py:1032
msgid "You must create a new filesystem on the root device."
msgstr ""

#: pyanaconda/storage/__init__.py:1185
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""

#: pyanaconda/storage/__init__.py:1190
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""

#: pyanaconda/storage/__init__.py:1201
#, python-format
msgid ""
"Your / partition is less than %(min)s MB which is lower than recommended for "
"a normal %(productName)s%(live)s install."
msgstr ""

#: pyanaconda/storage/__init__.py:1212
#, python-format
msgid ""
"Your / partition does not match the the live image you are installing from.  "
"It must be formatted as %s."
msgstr ""

#: pyanaconda/storage/__init__.py:1219
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""

#: pyanaconda/storage/__init__.py:1229
#, python-format
msgid ""
"Your %(mount)s partition is too small for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""

#: pyanaconda/storage/__init__.py:1234
#, python-format
msgid ""
"Your %(mount)s partition is too large for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""

#: pyanaconda/storage/__init__.py:1261
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""

#: pyanaconda/storage/__init__.py:1264
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""

#: pyanaconda/storage/__init__.py:1270
msgid "you have not created a bootloader stage1 target device"
msgstr ""

#: pyanaconda/storage/__init__.py:1279
msgid "You have not created a bootable partition."
msgstr ""

#: pyanaconda/storage/__init__.py:1292
#, python-format
msgid ""
"You have not specified a swap partition.  %(requiredMem)s MB of memory is "
"required to continue installation without a swap partition, but you only "
"have %(installedMem)s MB."
msgstr ""

#: pyanaconda/storage/__init__.py:1298
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""

#: pyanaconda/storage/__init__.py:1304
msgid ""
"At least one of your swap devices does not have a UUID, which is common in "
"swap space created using older versions of mkswap. These devices will be "
"referred to by device path in /etc/fstab, which is not ideal since device "
"paths can change under a variety of circumstances. "
msgstr ""

#: pyanaconda/storage/__init__.py:1314
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""

#: pyanaconda/storage/__init__.py:1318
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr ""

#: pyanaconda/storage/__init__.py:1329
msgid "No Drives Found"
msgstr ""

#: pyanaconda/storage/__init__.py:1330
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems. Please check your hardware for the cause of this problem."
msgstr ""

#: pyanaconda/storage/__init__.py:1697 pyanaconda/storage/__init__.py:1706
msgid "Dirty File Systems"
msgstr ""

#: pyanaconda/storage/__init__.py:1698
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Please boot your Linux installation, let the file systems be "
"checked and shut down cleanly to upgrade.\n"
"%s"
msgstr ""

#: pyanaconda/storage/__init__.py:1707
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""

#: pyanaconda/storage/__init__.py:2119
msgid ""
"There is an entry in your /etc/fstab file that contains an invalid or "
"incorrect filesystem type:\n"
"\n"
"  "
msgstr ""

#: pyanaconda/storage/__init__.py:2177
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"is an old-style Linux swap partition.  If you want to use this device for "
"swap space, you must reformat as a new-style Linux swap partition."
msgstr ""

#: pyanaconda/storage/__init__.py:2188
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. To perform an upgrade, please shut "
"down your system rather than hibernating it."
msgstr ""

#: pyanaconda/storage/__init__.py:2196
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. If you are performing a new install, "
"make sure the installer is set to format all swap devices."
msgstr ""

#: pyanaconda/storage/__init__.py:2208
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"does not contain a supported swap volume.  In order to continue "
"installation, you will need to format the device or skip it."
msgstr ""

#: pyanaconda/storage/__init__.py:2219
#, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s\n"
"\n"
"The /etc/fstab on your upgrade partition does not reference a valid swap "
"device.\n"
"\n"
"Press OK to exit the installer"
msgstr ""

#: pyanaconda/storage/__init__.py:2226
#, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s\n"
"\n"
"This most likely means this swap device has not been initialized.\n"
"\n"
"Press OK to exit the installer."
msgstr ""

#: pyanaconda/storage/__init__.py:2289 pyanaconda/storage/__init__.py:2301
msgid "Invalid mount point"
msgstr ""

#: pyanaconda/storage/__init__.py:2290
#, python-format
msgid ""
"An error occurred when trying to create %s.  Some element of this path is "
"not a directory. This is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""

#: pyanaconda/storage/__init__.py:2302
#, python-format
msgid ""
"An error occurred when trying to create %(mountpoint)s: %(msg)s.  This is a "
"fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""

#: pyanaconda/storage/__init__.py:2318 pyanaconda/storage/__init__.py:2342
msgid "Unable to mount filesystem"
msgstr ""

#: pyanaconda/storage/__init__.py:2319
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s.  You may "
"continue installation, but there may be problems."
msgstr ""

#: pyanaconda/storage/__init__.py:2343
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s: %(msg)s. This "
"is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""

#: pyanaconda/storage/dasd.py:155
msgid "Formatting DASD Device"
msgid_plural "Formatting DASD Devices"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/storage/dasd.py:156
#, python-format
msgid "Preparing %d DASD device for use with Linux..."
msgid_plural "Preparing %d DASD devices for use with Linux..."
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/storage/devicelibs/lvm.py:284
#, python-format
msgid "vginfo failed for %s"
msgstr ""

#: pyanaconda/storage/devicelibs/lvm.py:313
#, python-format
msgid "lvs failed for %s"
msgstr ""

#: pyanaconda/storage/devices.py:791
msgid "Creating"
msgstr ""

#: pyanaconda/storage/devices.py:792
#, python-format
msgid "Creating device %s"
msgstr ""

#: pyanaconda/storage/devices.py:2725
#, python-format
msgid "A RAID%(raidLevel)d set requires at least %(minMembers)d member"
msgid_plural "A RAID%(raidLevel)d set requires at least %(minMembers)d members"
msgstr[0] ""
msgstr[1] ""

#: pyanaconda/storage/devicetree.py:104
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""

#: pyanaconda/storage/fcoe.py:71 pyanaconda/storage/fcoe.py:72
msgid "Connecting to FCoE SAN"
msgstr ""

#: pyanaconda/storage/fcoe.py:116
msgid "FCoE not available"
msgstr ""

#: pyanaconda/storage/formats/fs.py:100
msgid "filesystem configuration missing a type"
msgstr ""

#: pyanaconda/storage/formats/fs.py:360 pyanaconda/storage/formats/luks.py:197
#: pyanaconda/storage/formats/lvmpv.py:105
#: pyanaconda/storage/formats/swap.py:161
msgid "Formatting"
msgstr ""

#: pyanaconda/storage/formats/fs.py:361
#, python-format
msgid "Creating %(type)s filesystem on %(device)s"
msgstr ""

#: pyanaconda/storage/formats/fs.py:463
msgid "Resizing"
msgstr ""

#: pyanaconda/storage/formats/fs.py:464
#, python-format
msgid "Resizing filesystem on %s"
msgstr ""

#: pyanaconda/storage/formats/fs.py:499
#, python-format
msgid "Unknown return code: %d."
msgstr ""

#: pyanaconda/storage/formats/fs.py:513
msgid "Checking"
msgstr ""

#: pyanaconda/storage/formats/fs.py:514
#, python-format
msgid "Checking filesystem on %s"
msgstr ""

#: pyanaconda/storage/formats/fs.py:531
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr ""

#: pyanaconda/storage/formats/fs.py:537
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair.  Before restarting installation, "
"reboot to rescue mode or another system that allows you to repair the "
"filesystem interactively.  Restart installation after you have corrected the "
"problems on the filesystem."
msgstr ""

#: pyanaconda/storage/formats/fs.py:545 pyanaconda/storage/partitioning.py:385
msgid "Unrecoverable Error"
msgstr ""

#: pyanaconda/storage/formats/fs.py:919
msgid "File system errors left uncorrected."
msgstr ""

#: pyanaconda/storage/formats/fs.py:920
msgid "Operational error."
msgstr ""

#: pyanaconda/storage/formats/fs.py:921
msgid "Usage or syntax error."
msgstr ""

#: pyanaconda/storage/formats/fs.py:922
msgid "e2fsck cancelled by user request."
msgstr ""

#: pyanaconda/storage/formats/fs.py:923
msgid "Shared library error."
msgstr ""

#: pyanaconda/storage/formats/fs.py:1091
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""

#: pyanaconda/storage/formats/fs.py:1093
msgid "Usage error."
msgstr ""

#: pyanaconda/storage/formats/luks.py:48
msgid "Encrypted"
msgstr ""

#: pyanaconda/storage/formats/luks.py:198
#, python-format
msgid "Encrypting %s"
msgstr ""

#: pyanaconda/storage/formats/lvmpv.py:106
#: pyanaconda/storage/formats/swap.py:162
#, python-format
msgid "Creating %(type)s on %(device)s"
msgstr ""

#: pyanaconda/storage/iscsi.py:120
msgid "Unable to change iSCSI initiator name once set"
msgstr ""

#: pyanaconda/storage/iscsi.py:122
msgid "Must provide an iSCSI initiator name"
msgstr ""

#: pyanaconda/storage/iscsi.py:153 pyanaconda/storage/iscsi.py:154
msgid "Scanning iSCSI nodes"
msgstr ""

#: pyanaconda/storage/iscsi.py:174 pyanaconda/storage/iscsi.py:175
msgid "Initializing iSCSI initiator"
msgstr ""

#: pyanaconda/storage/iscsi.py:230
msgid "iSCSI not available"
msgstr ""

#: pyanaconda/storage/iscsi.py:232
msgid "No initiator name set"
msgstr ""

#: pyanaconda/storage/iscsi.py:260
msgid "Logging in to iSCSI node"
msgstr ""

#: pyanaconda/storage/iscsi.py:261
#, python-format
msgid "Logging in to iSCSI node %s"
msgstr ""

#: pyanaconda/storage/partitioning.py:307
msgid ""
"Could not find enough free space for automatic partitioning.  Press 'OK' to "
"exit the installer."
msgstr ""

#: pyanaconda/storage/partitioning.py:310
msgid ""
"Could not find enough free space for automatic partitioning, please use "
"another partitioning method."
msgstr ""

#: pyanaconda/storage/partitioning.py:335
msgid "Warnings During Automatic Partitioning"
msgstr ""

#: pyanaconda/storage/partitioning.py:337
#, python-format
msgid ""
"Following warnings occurred during automatic partitioning:\n"
"\n"
"%s"
msgstr ""

#: pyanaconda/storage/partitioning.py:348
#: pyanaconda/storage/partitioning.py:369
msgid ""
"\n"
"\n"
"Press 'OK' to exit the installer."
msgstr ""

#: pyanaconda/storage/partitioning.py:352
#, python-format
msgid ""
"Could not allocate requested partitions: \n"
"\n"
"%(msg)s.%(extra)s"
msgstr ""

#: pyanaconda/storage/partitioning.py:371
msgid ""
"\n"
"\n"
"Press 'OK' to choose a different partitioning option."
msgstr ""

#: pyanaconda/storage/partitioning.py:373
msgid "Automatic Partitioning Errors"
msgstr ""

#: pyanaconda/storage/partitioning.py:374
#, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%(errortxt)s\n"
"\n"
"This can happen if there is not enough space on your hard drive(s) for the "
"installation. %(extra)s"
msgstr ""

#: pyanaconda/storage/zfcp.py:51
msgid "You have not specified a device number or the number is invalid"
msgstr ""

#: pyanaconda/storage/zfcp.py:53
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr ""

#: pyanaconda/storage/zfcp.py:55
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr ""

#: pyanaconda/storage/zfcp.py:133
#, python-format
msgid "zFCP device %s not found, not even in device ignore list."
msgstr ""

#: pyanaconda/storage/zfcp.py:143
#, python-format
msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:154
#, python-format
msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:161
#, python-format
msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
msgstr ""

#: pyanaconda/storage/zfcp.py:176
#, python-format
msgid ""
"Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)"
"s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:182
#, python-format
msgid ""
"LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already configured."
msgstr ""

#: pyanaconda/storage/zfcp.py:194
#, python-format
msgid ""
"Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on zFCP "
"device %(devnum)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:203
#, python-format
msgid ""
"Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
"again."
msgstr ""

#: pyanaconda/storage/zfcp.py:260
#, python-format
msgid ""
"Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s %(fcplun)"
"s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:269
#, python-format
msgid ""
"Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s (%"
"(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:287
#, python-format
msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
msgstr ""

#: pyanaconda/storage/zfcp.py:313
#, python-format
msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
msgstr ""

#: pyanaconda/textw/complete_text.py:32
msgid "Reboot"
msgstr ""

#: pyanaconda/textw/complete_text.py:34
msgid "<Enter> to exit"
msgstr ""

#: pyanaconda/textw/complete_text.py:62
msgid "Complete"
msgstr ""

#: pyanaconda/textw/constants_text.py:75
#, python-format
msgid ""
"This storage device may contain data:\n"
"\n"
"%(description)s, %(size)s MB, %(devicePath)s\n"
"\n"
"We could not detect partitions or filesystems on this device. This could be "
"because the device is blank, unpartitioned, or virtual. If not, there may be "
"data on the device that can not be recovered if you use it in this "
"installation. We can remove the device from this installation to protect the "
"data.\n"
"\n"
"Are you sure this device does not contain valuable data?"
msgstr ""

#: pyanaconda/textw/constants_text.py:88
msgid "Apply my choice to all devices with undetected partitions."
msgstr ""

#: pyanaconda/textw/keyboard_text.py:48
msgid "Keyboard Selection"
msgstr ""

#: pyanaconda/textw/keyboard_text.py:49
msgid "Which model keyboard is attached to this computer?"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:35 pyanaconda/textw/netconfig_text.py:42
msgid "Error With Data"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:36
#, python-format
msgid ""
"An error occurred converting the value entered for \"%(field)s\":\n"
"%(errmsg)s"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:43
#, python-format
msgid "A value is required for the field %s"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:126
#: pyanaconda/textw/netconfig_text.py:152
msgid "Enable network interface"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:129
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please select network interface to configure."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:155
#, python-format
msgid "Configure interface %s to be used during installation process."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:160
msgid "Enable IPv4 Support"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:164
msgid "Dynamic IP configuration (DHCP)"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:167
#: pyanaconda/textw/netconfig_text.py:207
msgid "Manual Configuration"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:175
msgid "IPv4 Address:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:184
#: pyanaconda/textw/netconfig_text.py:224
msgid "Gateway:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:189
#: pyanaconda/textw/netconfig_text.py:229
msgid "Nameserver:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:197
msgid "Enable IPv6 Support"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:201
msgid "Automatic neighbor discovery"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:204
msgid "Dynamic IP Configuration (DHCPv6)"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:215
msgid "IPv6 Address:"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:270
msgid "Missing protocol"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:271
msgid "You must select at least one protocol version"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:279
#: pyanaconda/textw/netconfig_text.py:282
msgid "IPv4 Address"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:286
#: pyanaconda/textw/netconfig_text.py:291
msgid "IPv4 Prefix"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:290
msgid "IPv4 CIDR prefix must be between 0 and 32."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:298
msgid "IPv4 Gateway"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:307
msgid "IPv4 Nameserver"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:315
#: pyanaconda/textw/netconfig_text.py:318
msgid "IPv6 Address"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:322
#: pyanaconda/textw/netconfig_text.py:327
msgid "IPv6 Prefix"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:326
msgid "IPv6 CIDR prefix must be between 0 and 128."
msgstr ""

#: pyanaconda/textw/netconfig_text.py:334
msgid "IPv6 Gateway"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:342
msgid "IPv6 Nameserver"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:399
msgid "Configuring Network Interfaces"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:403
msgid "Network Error"
msgstr ""

#: pyanaconda/textw/netconfig_text.py:404
#, python-format
msgid "There was an error configuring network device %s"
msgstr ""

#: pyanaconda/textw/partition_text.py:58
msgid "Partitioning Type"
msgstr ""

#: pyanaconda/textw/partition_text.py:60
msgid ""
"Installation requires partitioning of your hard drive.  The default layout "
"is suitable for most users.  Select what space to use and which drives to "
"use as the install target."
msgstr ""

#: pyanaconda/textw/partition_text.py:63
msgid "Use entire drive"
msgstr ""

#: pyanaconda/textw/partition_text.py:64
msgid "Replace existing Linux system"
msgstr ""

#: pyanaconda/textw/partition_text.py:65
msgid "Use free space"
msgstr ""

#: pyanaconda/textw/partition_text.py:80
msgid "Which drive(s) do you want to use for this installation?"
msgstr ""

#: pyanaconda/textw/partition_text.py:95
msgid "<Space>,<+>,<-> selection   |   <F2> Add drive   |   <F12> next screen"
msgstr ""

#: pyanaconda/textw/progress_text.py:46
msgid "Package Installation"
msgstr ""

#: pyanaconda/textw/timezone_text.py:52
msgid "In which time zone are you located?"
msgstr ""

#: pyanaconda/textw/timezone_text.py:64
msgid "System clock uses UTC"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:117
msgid "Reinstall System"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:126
msgid "System to Upgrade"
msgstr ""

#: pyanaconda/textw/upgrade_text.py:127
msgid ""
"There seem to be one or more existing Linux installations on your system.\n"
"\n"
"Please choose one to upgrade, or select 'Reinstall System' to freshly "
"install your system."
msgstr ""

#: pyanaconda/textw/userauth_text.py:30
msgid "Root Password"
msgstr ""

#: pyanaconda/textw/userauth_text.py:33
msgid ""
"Pick a root password. You must type it twice to ensure you know it and do "
"not make a typing mistake. "
msgstr ""

#: pyanaconda/textw/userauth_text.py:67
msgid "The root password must be at least 6 characters long."
msgstr ""

#: pyanaconda/textw/userauth_text.py:85
#, python-format
msgid ""
"You have provided a weak password: %s\n"
"\n"
"Would you like to continue with this password?"
msgstr ""

#: pyanaconda/textw/zipl_text.py:35
msgid ""
"The z/IPL Boot Loader will be installed on your system after installation is "
"complete. You can now enter any additional kernel parameters required by "
"your machine or setup."
msgstr ""

#: pyanaconda/textw/zipl_text.py:50
msgid "z/IPL Configuration"
msgstr ""

#: data/liveinst/gnome/fedora-welcome:64
msgid "Welcome to Fedora"
msgstr ""

#: data/liveinst/gnome/fedora-welcome:93
msgid "Try Fedora"
msgstr ""

#: data/liveinst/gnome/fedora-welcome:111
msgid ""
"You are currently running Fedora from live media.\n"
"You can install Fedora now, or choose \"Install to Hard Drive\" in the "
"Activities Overview at any later time."
msgstr ""

#: data/liveinst/gnome/fedora-welcome:129
msgid ""
"You can choose \"Install to Hard Drive\"\n"
"in the Activities Overview at any later time."
msgstr ""

#: data/liveinst/gnome/fedora-welcome:132
msgid "Close"
msgstr ""

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install"
msgstr ""

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install the live CD to your hard disk"
msgstr ""

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install to Hard Drive"
msgstr ""

#: liveinst:5
msgid "Starting Install to Hard Drive"
msgstr ""

#: data/ui/GroupSelector.glade.h:1
msgid ""
"Some packages associated with this group are not required to be installed "
"but may provide additional functionality.  Please choose the packages which "
"you would like to have installed."
msgstr ""

#: data/ui/GroupSelector.glade.h:2
msgid "_Deselect"
msgstr ""

#: data/ui/GroupSelector.glade.h:3
msgid "_Deselect all optional packages"
msgstr ""

#: data/ui/GroupSelector.glade.h:4
msgid "_Optional packages"
msgstr ""

#: data/ui/GroupSelector.glade.h:5
msgid "_Select"
msgstr ""

#: data/ui/GroupSelector.glade.h:6
msgid "_Select all optional packages"
msgstr ""

#: data/ui/GroupSelector.glade.h:7
msgid "dialog1"
msgstr ""

#: data/ui/account.glade.h:1
msgid "Confirm:"
msgstr ""

#: data/ui/account.glade.h:2
msgid "Root Password:"
msgstr ""

#: data/ui/account.glade.h:3
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""

#: data/ui/adddrive.glade.h:1
msgid "Add _FCoE SAN"
msgstr ""

#: data/ui/adddrive.glade.h:2
msgid "Add _ZFCP LUN"
msgstr ""

#: data/ui/adddrive.glade.h:3
msgid "Add _iSCSI target"
msgstr ""

#: data/ui/adddrive.glade.h:4
msgid "Advanced Storage Options"
msgstr ""

#: data/ui/adddrive.glade.h:5
msgid "How would you like to modify your drive configuration?"
msgstr ""

#: data/ui/adddrive.glade.h:6
msgid "_Add drive"
msgstr ""

#: data/ui/addrepo.glade.h:1
msgid "<b>Repository _name:</b>"
msgstr ""

#: data/ui/addrepo.glade.h:2
msgid "<b>Repository _type:</b>"
msgstr ""

#: data/ui/addrepo.glade.h:4
msgid "Configure _proxy"
msgstr ""

#: data/ui/addrepo.glade.h:5
msgid ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"Hard Drive"
msgstr ""

#: data/ui/addrepo.glade.h:9
msgid "Opt_ions"
msgstr ""

#: data/ui/addrepo.glade.h:10
msgid ""
"Please provide the configuration information for this software repository."
msgstr ""

#: data/ui/addrepo.glade.h:11
msgid "Proxy U_RL (host:port)"
msgstr ""

#: data/ui/addrepo.glade.h:12
msgid "Proxy pass_word"
msgstr ""

#: data/ui/addrepo.glade.h:13
msgid "Proxy u_sername"
msgstr ""

#: data/ui/addrepo.glade.h:14
msgid "Repository _URL"
msgstr ""

#: data/ui/addrepo.glade.h:15
msgid "Select A Directory"
msgstr ""

#: data/ui/addrepo.glade.h:16
msgid "URL is a _mirror list"
msgstr ""

#: data/ui/addrepo.glade.h:17
msgid "_Directory"
msgstr ""

#: data/ui/addrepo.glade.h:18
msgid "_Partition"
msgstr ""

#: data/ui/addrepo.glade.h:19
msgid "_Path"
msgstr ""

#: data/ui/addrepo.glade.h:20
msgid "_Server"
msgstr ""

#: data/ui/anaconda.glade.h:1
msgid "Reboo_t"
msgstr ""

#: data/ui/anaconda.glade.h:4
msgid "_Next"
msgstr ""

#: data/ui/autopart.glade.h:1
msgid "<b>Shrink partition _to size (in MB):</b>"
msgstr ""

#: data/ui/autopart.glade.h:2
msgid "Re_view and modify partitioning layout"
msgstr ""

#: data/ui/autopart.glade.h:3
msgid "Use _LVM"
msgstr ""

#: data/ui/autopart.glade.h:4
msgid "Volume to Shrink"
msgstr ""

#: data/ui/autopart.glade.h:5
msgid ""
"Which partition would you like to shrink to make room for your installation?"
msgstr ""

#: data/ui/autopart.glade.h:6
msgid "Which type of installation would you like?"
msgstr ""

#: data/ui/autopart.glade.h:7
msgid "_Encrypt system"
msgstr ""

#: data/ui/autopart.glade.h:8
msgid "_Shrink"
msgstr ""

#: data/ui/blwhere.glade.h:1
msgid "/boot"
msgstr ""

#: data/ui/blwhere.glade.h:2
msgid "BIOS Drive Order"
msgstr ""

#: data/ui/blwhere.glade.h:3
msgid "Boot loader device"
msgstr ""

#: data/ui/blwhere.glade.h:4
msgid "First BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:5
msgid "Fourth BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:6
msgid "MBR"
msgstr ""

#: data/ui/blwhere.glade.h:7
msgid "Second BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:8
msgid "Third BIOS drive:"
msgstr ""

#: data/ui/blwhere.glade.h:9
msgid "Where would you like to install the boot loader for your system?"
msgstr ""

#: data/ui/cleardisks.glade.h:1
msgid "<b>Data Storage Devices</b> (to be mounted only)"
msgstr ""

#: data/ui/cleardisks.glade.h:2
msgid "<b>Install Target Devices</b>"
msgstr ""

#: data/ui/cleardisks.glade.h:3
msgid ""
"<b>Tip:</b> Install target devices will be reformatted and wiped of any "
"data.  Make sure you have backups."
msgstr ""

#: data/ui/cleardisks.glade.h:4
msgid ""
"Below are the storage devices you've selected to be a part of this "
"installation.  Please indicate using the arrows below which devices you'd "
"like to use as data devices (these will not be formatted, only mounted) and "
"which devices you'd like to use as installation target devices (these may be "
"formatted).  Please also indicate which system drive will have the "
"bootloader installed."
msgstr ""

#: data/ui/create-storage.glade.h:1
msgid ""
"<span size=\"small\" color=\"gray\">Create a RAID formatted partition</span>"
msgstr ""

#: data/ui/create-storage.glade.h:2
msgid ""
"<span size=\"small\" color=\"gray\">Create a logical volume on selected "
"volume group</span>"
msgstr ""

#: data/ui/create-storage.glade.h:3
msgid ""
"<span size=\"small\" color=\"gray\">Create an LVM formatted partition</span>"
msgstr ""

#: data/ui/create-storage.glade.h:4
msgid ""
"<span size=\"small\" color=\"gray\">General purpose partition creation</span>"
msgstr ""

#: data/ui/create-storage.glade.h:5
msgid ""
"<span size=\"small\" color=\"gray\">Requires at least 1 free LVM formatted "
"partition</span>"
msgstr ""

#: data/ui/create-storage.glade.h:6
msgid ""
"<span size=\"small\" color=\"gray\">Requires at least 2 free RAID formatted "
"partitions</span>"
msgstr ""

#: data/ui/create-storage.glade.h:7
msgid "C_reate"
msgstr ""

#: data/ui/create-storage.glade.h:8
msgid "Create LVM"
msgstr ""

#: data/ui/create-storage.glade.h:9
msgid "Create Partition"
msgstr ""

#: data/ui/create-storage.glade.h:10
msgid "Create Software RAID"
msgstr ""

#: data/ui/create-storage.glade.h:11
msgid "Create Storage"
msgstr ""

#: data/ui/create-storage.glade.h:12
msgid "LVM Logical Volume"
msgstr ""

#: data/ui/create-storage.glade.h:13
msgid "LVM Physical Volume"
msgstr ""

#: data/ui/create-storage.glade.h:14
msgid "LVM Volume Group"
msgstr ""

#: data/ui/create-storage.glade.h:16
msgid "RAID Partition"
msgstr ""

#: data/ui/create-storage.glade.h:17
msgid "Standard Partition"
msgstr ""

#: data/ui/detailed-dialog.glade.h:1
msgid "Info"
msgstr ""

#: data/ui/detailed-dialog.glade.h:2
msgid "_Details"
msgstr ""

#: data/ui/device-options.glade.h:1
msgid "Device Options"
msgstr ""

#: data/ui/device-options.glade.h:2
msgid ""
"If enabled the multipath devices are named following the /dev/mapper/"
"mpath<letter> format instead of /dev/mapper/<wwid>. Note that the user "
"friendly names are assigned by multipath tools and are not guaranteed to be "
"the same between installs."
msgstr ""

#: data/ui/device-options.glade.h:3
msgid "Use _friendly names for multipath devices"
msgstr ""

#: data/ui/fcoe-config.glade.h:1
msgid "Configure FCoE Parameters"
msgstr ""

#: data/ui/fcoe-config.glade.h:2
msgid "NIC:"
msgstr ""

#: data/ui/fcoe-config.glade.h:3
msgid ""
"Please select the network interface which is connected to\n"
"your FCoE switch."
msgstr ""

#: data/ui/fcoe-config.glade.h:5
msgid "Use DCB"
msgstr ""

#: data/ui/fcoe-config.glade.h:6
msgid "_Add FCoE Disk(s)"
msgstr ""

#: data/ui/filter.glade.h:1
msgid ""
"<b>Tip:</b> Selected drives will not be formatted unless you choose to do so "
"later during installation.  Also, note that post-installation you may mount "
"drives you did not select here by modifying your /etc/fstab file."
msgstr ""

#: data/ui/filter.glade.h:2
msgid "Basic Devices"
msgstr ""

#: data/ui/filter.glade.h:3
msgid "Filter By:"
msgstr ""

#: data/ui/filter.glade.h:4
msgid "Firmware RAID"
msgstr ""

#: data/ui/filter.glade.h:5
msgid "Identifier:"
msgstr ""

#: data/ui/filter.glade.h:6
msgid ""
"Interconnect\n"
"Vendor\n"
"Identifier"
msgstr ""

#: data/ui/filter.glade.h:9
msgid "LUN:"
msgstr ""

#: data/ui/filter.glade.h:10
msgid "Multipath Devices"
msgstr ""

#: data/ui/filter.glade.h:11
msgid "Other SAN Devices"
msgstr ""

#: data/ui/filter.glade.h:12
msgid ""
"Please select the drives you'd like to install the operating system on, as "
"well as any drives you'd like to automatically mount on your system:"
msgstr ""

#: data/ui/filter.glade.h:13
msgid ""
"Port / Target / LUN\n"
"Target Identifier"
msgstr ""

#: data/ui/filter.glade.h:15
msgid "Port:"
msgstr ""

#: data/ui/filter.glade.h:16
msgid "Search"
msgstr ""

#: data/ui/filter.glade.h:17
msgid "Search By:"
msgstr ""

#: data/ui/filter.glade.h:18
msgid "Search Results:"
msgstr ""

#: data/ui/filter.glade.h:20
#, no-c-format
msgid "Selected devices: %s (%s) out of %s (%s)."
msgstr ""

#: data/ui/filter.glade.h:21
msgid "Show Identifiers that Include:"
msgstr ""

#: data/ui/filter.glade.h:22
msgid "Show Only Devices From:"
msgstr ""

#: data/ui/filter.glade.h:23
msgid "Show Only Devices Using:"
msgstr ""

#: data/ui/filter.glade.h:24
msgid "Target:"
msgstr ""

#: data/ui/filter.glade.h:25
msgid "_Add Advanced Target"
msgstr ""

#: data/ui/filter.glade.h:26
msgid "_Device Options"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:1
msgid "CHAP Password:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:2
msgid "CHAP Username:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:3
msgid "Check the nodes you wish to log into:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:4
msgid "Reason:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:5
msgid "Retry _Login"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:6
msgid "Reverse CHAP Password:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:7
msgid "Reverse CHAP Username:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:8
msgid "Start _Discovery"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:9
msgid "Successfully logged in and attached the following nodes:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:10
msgid "Target IP Address:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:11
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:12
msgid ""
"What kind of iSCSI <b>discovery authentication</b> do you wish to perform:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:13
msgid "What kind of iSCSI <b>login authentication</b> do you wish to perform:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:14
msgid "_Cancel"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:15
msgid "_Login"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:16
msgid "_OK"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:17
msgid "iSCSI Discovered Nodes"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:18
msgid "iSCSI Discovery Details"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:19
msgid "iSCSI Initiator Name:"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:20
msgid "iSCSI Login Results"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:21
msgid "iSCSI Nodes Login"
msgstr ""

#: data/ui/iscsi-dialogs.glade.h:22
msgid "iSCSI login has failed for the following nodes:"
msgstr ""

#: data/ui/lukspassphrase.glade.h:1
msgid ""
"Also add this passphrase to all existing encrypted devices to streamline the "
"boot process"
msgstr ""

#: data/ui/lukspassphrase.glade.h:2
msgid ""
"Choose a passphrase for this encrypted partition. You will be prompted for "
"the passphrase during system boot."
msgstr ""

#: data/ui/lukspassphrase.glade.h:3
msgid "Confirm passphrase:"
msgstr ""

#: data/ui/lukspassphrase.glade.h:4
msgid "Enter passphrase for encrypted partition"
msgstr ""

#: data/ui/lukspassphrase.glade.h:5
msgid "Enter passphrase:"
msgstr ""

#: data/ui/network.glade.h:1
msgid "Hostname:"
msgstr ""

#: data/ui/network.glade.h:2
msgid ""
"Please name this computer.  The hostname identifies the computer on a "
"network."
msgstr ""

#: data/ui/network.glade.h:3
msgid "_Configure Network"
msgstr ""

#: data/ui/tasksel.glade.h:1
msgid "Customize _later"
msgstr ""

#: data/ui/tasksel.glade.h:2
msgid ""
"Please select any additional repositories that you want to use for software "
"installation."
msgstr ""

#: data/ui/tasksel.glade.h:4
#, no-c-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage.  What additional tasks would you like your system to "
"support?"
msgstr ""

#: data/ui/tasksel.glade.h:5
msgid ""
"You can further customize the software selection now, or after install via "
"the software management application."
msgstr ""

#: data/ui/tasksel.glade.h:6
msgid "_Add additional software repositories"
msgstr ""

#: data/ui/tasksel.glade.h:7
msgid "_Customize now"
msgstr ""

#: data/ui/tasksel.glade.h:8
msgid "_Modify repository"
msgstr ""

#: data/ui/zfcp-config.glade.h:1
msgid "<b>Device number:</b>"
msgstr ""

#: data/ui/zfcp-config.glade.h:2
msgid "<b>FCP LUN:</b>"
msgstr ""

#: data/ui/zfcp-config.glade.h:3
msgid "<b>WWPN:</b>"
msgstr ""

#: data/ui/zfcp-config.glade.h:4
msgid "Add FCP device"
msgstr ""

#: data/ui/zfcp-config.glade.h:5
msgid ""
"zSeries machines can access industry-standard SCSI devices via Fibre Channel "
"(FCP). You need to provide a 16 bit device number, a 64 bit World Wide Port "
"Name (WWPN), and a 64 bit FCP LUN for each device."
msgstr ""

#: data/ui/reinitialize-dialog.glade.h:1
msgid ""
"<span size=\"large\" weight=\"bold\">The storage device below may contain "
"data.</span>"
msgstr ""

#: data/ui/reinitialize-dialog.glade.h:2
msgid ""
"Apply my choice to all devices with undetected partitions or filesystems."
msgstr ""

#: data/ui/reinitialize-dialog.glade.h:4
msgid ""
"We could not detect partitions or filesystems on this device.\n"
"\n"
"This could be because the device is <b>blank</b>, <b>unpartitioned</b>, or "
"<b>virtual</b>. If not, there may be data on the device that can not be "
"recovered if you use it in this installation. We can remove the device from "
"this installation to protect the data.\n"
"\n"
"Are you sure this device does not contain valuable data?"
msgstr ""

#: data/ui/reinitialize-dialog.glade.h:9
msgid "_No, keep any data"
msgstr ""

#: data/ui/reinitialize-dialog.glade.h:10
msgid "_Yes, discard any data"
msgstr ""

#: data/lang-table.h:1
msgid "Afrikaans"
msgstr ""

#: data/lang-table.h:2
msgid "Arabic"
msgstr ""

#: data/lang-table.h:3
msgid "Assamese"
msgstr ""

#: data/lang-table.h:4
msgid "Bengali"
msgstr ""

#: data/lang-table.h:5
msgid "Bengali(India)"
msgstr ""

#: data/lang-table.h:6
msgid "Bulgarian"
msgstr ""

#: data/lang-table.h:7
msgid "Catalan"
msgstr ""

#: data/lang-table.h:8
msgid "Chinese(Simplified)"
msgstr ""

#: data/lang-table.h:9
msgid "Chinese(Traditional)"
msgstr ""

#: data/lang-table.h:10
msgid "Croatian"
msgstr ""

#: data/lang-table.h:11
msgid "Czech"
msgstr ""

#: data/lang-table.h:12
msgid "Danish"
msgstr ""

#: data/lang-table.h:13
msgid "Dutch"
msgstr ""

#: data/lang-table.h:14
msgid "English"
msgstr ""

#: data/lang-table.h:15
msgid "Estonian"
msgstr ""

#: data/lang-table.h:16
msgid "Finnish"
msgstr ""

#: data/lang-table.h:17
msgid "French"
msgstr ""

#: data/lang-table.h:18
msgid "German"
msgstr ""

#: data/lang-table.h:19
msgid "Greek"
msgstr ""

#: data/lang-table.h:20
msgid "Gujarati"
msgstr ""

#: data/lang-table.h:21
msgid "Hebrew"
msgstr ""

#: data/lang-table.h:22
msgid "Hindi"
msgstr ""

#: data/lang-table.h:23
msgid "Hungarian"
msgstr ""

#: data/lang-table.h:24
msgid "Icelandic"
msgstr ""

#: data/lang-table.h:25
msgid "Iloko"
msgstr ""

#: data/lang-table.h:26
msgid "Indonesian"
msgstr ""

#: data/lang-table.h:27
msgid "Italian"
msgstr ""

#: data/lang-table.h:28
msgid "Japanese"
msgstr ""

#: data/lang-table.h:29
msgid "Kannada"
msgstr ""

#: data/lang-table.h:30
msgid "Korean"
msgstr ""

#: data/lang-table.h:31
msgid "Macedonian"
msgstr ""

#: data/lang-table.h:32
msgid "Maithili"
msgstr ""

#: data/lang-table.h:33
msgid "Malay"
msgstr ""

#: data/lang-table.h:34
msgid "Malayalam"
msgstr ""

#: data/lang-table.h:35
msgid "Marathi"
msgstr ""

#: data/lang-table.h:36
msgid "Nepali"
msgstr ""

#: data/lang-table.h:37
msgid "Norwegian(Bokmål)"
msgstr ""

#: data/lang-table.h:38
msgid "Northern Sotho"
msgstr ""

#: data/lang-table.h:39
msgid "Oriya"
msgstr ""

#: data/lang-table.h:40
msgid "Persian"
msgstr ""

#: data/lang-table.h:41
msgid "Polish"
msgstr ""

#: data/lang-table.h:42
msgid "Portuguese"
msgstr ""

#: data/lang-table.h:43
msgid "Portuguese(Brazilian)"
msgstr ""

#: data/lang-table.h:44
msgid "Punjabi"
msgstr ""

#: data/lang-table.h:45
msgid "Romanian"
msgstr ""

#: data/lang-table.h:46
msgid "Russian"
msgstr ""

#: data/lang-table.h:47
msgid "Serbian"
msgstr ""

#: data/lang-table.h:48
msgid "Serbian(Latin)"
msgstr ""

#: data/lang-table.h:49
msgid "Sinhala"
msgstr ""

#: data/lang-table.h:50
msgid "Slovak"
msgstr ""

#: data/lang-table.h:51
msgid "Slovenian"
msgstr ""

#: data/lang-table.h:52
msgid "Spanish"
msgstr ""

#: data/lang-table.h:53
msgid "Swedish"
msgstr ""

#: data/lang-table.h:54
msgid "Tajik"
msgstr ""

#: data/lang-table.h:55
msgid "Tamil"
msgstr ""

#: data/lang-table.h:56
msgid "Telugu"
msgstr ""

#: data/lang-table.h:57
msgid "Turkish"
msgstr ""

#: data/lang-table.h:58
msgid "Ukrainian"
msgstr ""

#: data/lang-table.h:59
msgid "Vietnamese"
msgstr ""

#: data/lang-table.h:60
msgid "Welsh"
msgstr ""

#: data/lang-table.h:61
msgid "Zulu"
msgstr ""
